apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adapter-pvc
  namespace: lora-serving
  labels:
    app: vllm-lora
    app.kubernetes.io/name: vllm-lora
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp2
