apiVersion: v1
kind: Service
metadata:
  name: {{ include "lorax.fullname" . }}
  labels:
    app: {{ include "lorax.name" . }}
    chart: {{ include "lorax.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
  {{- if .Values.metrics.enabled }}
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
    protocol: TCP
  {{- end }}
  selector:
    app: {{ include "lorax.name" . }}
    release: {{ .Release.Name }}
