#!/usr/bin/env python3
"""
Provider Profiles — Encodes provider-specific quirks and behaviors.

Each provider has unique API patterns, auth methods, capacity constraints,
and lifecycle quirks. These profiles enable intelligent routing decisions
in ProviderRegistry and CLI.
"""

from .types import ProviderProfile

# Provider profiles based on audit of provider implementations
PROVIDER_PROFILES: dict[str, ProviderProfile] = {
    "runpod": ProviderProfile(
        name="runpod",
        api_style="graphql",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="graphql",
        volume_required_for_persistence=True,
        volume_cost_separate=True,
        data_loss_on_restart=True,
        egress_cost=0.0,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=100,
        compute_model="pod",
        isolation_level="container",
        has_multi_tier_cloud=True,  # Community vs Secure
        supports_stop_start=True,
    ),
    "vastai": ProviderProfile(
        name="vastai",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="post_filter",  # POST /bundles/ with JSON filter
        egress_cost=0.01,
        ssh_port_fixed=False,  # Dynamic SSH port per instance
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "aws": ProviderProfile(
        name="aws",
        api_style="rest",
        auth_type="service_account",  # access_key + secret_key
        requires_instance_type_mapping=True,  # gpu_type → ec2_instance_type
        quote_method="get",
        egress_cost=0.09,  # $0.09/GB outbound
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=2,
        spot_preemption_webhook=True,  # CloudWatch Events
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        requires_boto3=True,
        has_capacity_reservations=True,
        supports_stop_start=True,
    ),
    "gcp": ProviderProfile(
        name="gcp",
        api_style="rest",
        auth_type="service_account",  # JSON credentials file
        requires_instance_type_mapping=True,
        quote_method="get",
        egress_cost=0.12,  # $0.12/GB outbound
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        requires_gcp_sdk=True,
        has_capacity_reservations=True,
        requires_zone_probing=True,  # H100 availability varies by zone
        supports_stop_start=True,
    ),
    "azure": ProviderProfile(
        name="azure",
        api_style="rest",
        auth_type="service_account",
        requires_instance_type_mapping=True,
        quote_method="get",
        egress_cost=0.087,  # $0.087/GB outbound
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "lambda_labs": ProviderProfile(
        name="lambda_labs",
        api_style="rest",
        auth_type="basic",  # HTTP Basic: base64(api_key+":")
        requires_instance_type_mapping=False,
        quote_method="get",
        has_capacity_check=True,
        has_fallback_routing=True,
        fallback_providers=["runpod", "vastai", "tensordock"],
        egress_cost=0.0,  # No egress costs
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=False,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        container_conflict_risk=True,  # Lambda Stack conflicts
        container_image_pinning_required=True,
        supports_stop_start=False,
        supports_terminate_only=True,
    ),
    "crusoe": ProviderProfile(
        name="crusoe",
        api_style="rest",
        auth_type="hmac_sha256",  # Per-request HMAC-SHA256 signing
        requires_instance_type_mapping=False,
        quote_method="get",
        provision_requires_location_id=True,
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "digitalocean": ProviderProfile(
        name="digitalocean",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=False,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        region_specific_availability=True,
        supports_stop_start=True,
    ),
    "yottalabs": ProviderProfile(
        name="yottalabs",
        api_style="rest",
        auth_type="x_api_key",  # X-Api-Key header (NOT Bearer)
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="pod",
        isolation_level="container",
        supports_stop_start=True,
    ),
    "tensordock": ProviderProfile(
        name="tensordock",
        api_style="jsonapi",  # JSON:API-style envelope
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        provision_requires_location_id=True,
        egress_cost=0.005,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=False,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "coreweave": ProviderProfile(
        name="coreweave",
        api_style="k8s",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        provision_requires_namespace=True,
        has_capacity_check=True,
        has_legacy_billing=True,
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="k8s",
        isolation_level="k8s_pod",
        supports_stop_start=True,
    ),
    "fluidstack": ProviderProfile(
        name="fluidstack",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "hyperstack": ProviderProfile(
        name="hyperstack",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "oracle": ProviderProfile(
        name="oracle",
        api_style="rest",
        auth_type="service_account",  # RSA signing limitation
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "ovhcloud": ProviderProfile(
        name="ovhcloud",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "hetzner": ProviderProfile(
        name="hetzner",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=False,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "siliconflow": ProviderProfile(
        name="siliconflow",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "alibaba": ProviderProfile(
        name="alibaba",
        api_style="rest",
        auth_type="service_account",
        requires_instance_type_mapping=True,
        quote_method="get",
        egress_cost=0.08,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "e2e_networks": ProviderProfile(
        name="e2e_networks",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=False,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "baseten": ProviderProfile(
        name="baseten",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=False,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "inferx": ProviderProfile(
        name="inferx",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "latitude": ProviderProfile(
        name="latitude",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
    "huggingface": ProviderProfile(
        name="huggingface",
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=False,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    ),
}


def get_profile(provider_name: str) -> ProviderProfile:
    """Get provider profile by name. Returns default profile if not found."""
    return PROVIDER_PROFILES.get(provider_name.lower(), _default_profile(provider_name))


def _default_profile(provider_name: str) -> ProviderProfile:
    """Default profile for unknown providers (conservative defaults)."""
    return ProviderProfile(
        name=provider_name,
        api_style="rest",
        auth_type="bearer",
        requires_instance_type_mapping=False,
        quote_method="get",
        egress_cost=0.0,
        ssh_port_fixed=True,
        ssh_default_port=22,
        supports_spot=True,
        spot_interruption_notice_minutes=0,
        rate_limit_per_minute=0,
        compute_model="vm",
        isolation_level="vm",
        supports_stop_start=True,
    )


def list_all_profiles() -> dict[str, ProviderProfile]:
    """Get all provider profiles."""
    return PROVIDER_PROFILES.copy()
