#!/usr/bin/env python3
"""
Provider API contract tests.

These tests mock the HTTP layer and verify that the JSON payloads, URL paths,
and request shapes we send to each cloud provider still match their current
public API contracts. They are designed to fail when a provider changes
required fields, pagination, endpoint paths, or response keys — i.e. the exact
drift that passes local unit tests but breaks in production.

Snapshots are stored in tests/snapshots/provider_contracts/*.json and can be
regenerated by deleting the snapshot and re-running the test.
"""

import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List
from unittest.mock import patch

import pytest

SNAPSHOT_DIR = Path(__file__).parent / "snapshots" / "provider_contracts"


def _normalize_runpod_payload(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Remove dynamic/timestamp fields from RunPod pod spec for stable snapshots."""
    out = json.loads(json.dumps(payload, default=str))
    if not isinstance(out, dict):
        return out
    # Normalize inside preflight payload shape
    if isinstance(out.get("pod_spec"), dict) and "name" in out["pod_spec"]:
        out["pod_spec"]["name"] = re.sub(r"-\d{14}$", "-<TIMESTAMP>", out["pod_spec"]["name"])
    # Normalize inside actual captured GraphQL request variables/input/name
    if (
        isinstance(out.get("variables"), dict)
        and isinstance(out["variables"].get("input"), dict)
        and "name" in out["variables"]["input"]
    ):
        out["variables"]["input"]["name"] = re.sub(
            r"-\d{14}$", "-<TIMESTAMP>", out["variables"]["input"]["name"]
        )
    return out


def _write_snapshot(provider: str, label: str, data: Any):
    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    path = SNAPSHOT_DIR / f"{provider}_{label}.json"
    with open(path, "w") as f:
        json.dump(data, f, indent=2, default=str)


def _read_snapshot(provider: str, label: str) -> Any:
    path = SNAPSHOT_DIR / f"{provider}_{label}.json"
    if not path.exists():
        return None
    with open(path) as f:
        return json.load(f)


def _assert_matches_snapshot(provider: str, label: str, actual: Any):
    """Compare actual request shape to snapshot; create snapshot if missing."""
    normalized = _normalize_runpod_payload(actual) if provider == "runpod" else actual
    snapshot = _read_snapshot(provider, label)
    if snapshot is None:
        _write_snapshot(provider, label, normalized)
        pytest.skip(f"Created new snapshot for {provider}/{label}: run again to verify")
    assert normalized == snapshot, (
        f"{provider}/{label} request shape drifted from snapshot.\n"
        f"Expected: {json.dumps(snapshot, indent=2)}\n"
        f"Actual:   {json.dumps(normalized, indent=2)}"
    )


@pytest.mark.asyncio
async def test_runpod_provision_payload_contract():
    """Verify RunPod provision_instance builds the expected GraphQL pod spec."""
    from terradev_cli.providers.runpod_provider import RunPodProvider

    provider = RunPodProvider({"api_key": "test-key"})
    captured: List[Dict[str, Any]] = []

    async def _fake_make_request(method, url, **kwargs):
        captured.append({
            "method": method,
            "url": url,
            "headers": kwargs.get("headers", {}),
            "json": kwargs.get("json"),
            "data": kwargs.get("data"),
        })
        query = (kwargs.get("json") or {}).get("query", "")
        if "podFindAndDeployOnDemand" in query:
            return {
                "data": {
                    "podFindAndDeployOnDemand": {
                        "id": "pod-12345",
                        "name": "terradev-rtx4090-<TIMESTAMP>",
                        "gpuCount": 1,
                        "desiredStatus": "RUNNING",
                    }
                }
            }
        # Default for any other GraphQL call
        return {"data": {}}

    with patch.object(provider, "_make_request", _fake_make_request):
        result = await provider.provision_instance(
            instance_type="runpod-community-rtx4090",
            region="us-east",
            gpu_type="RTX4090",
            attach_volume=False,
        )

    assert result.get("instance_id") == "pod-12345"
    assert len(captured) >= 1

    deploy_call = None
    for call in captured:
        if call["url"] == "https://api.runpod.io/graphql" and call["json"]:
            if "podFindAndDeployOnDemand" in str(call["json"].get("query", "")):
                deploy_call = call
                break

    assert deploy_call is not None, "podFindAndDeployOnDemand GraphQL call not captured"
    _assert_matches_snapshot("runpod", "provision_payload", deploy_call["json"])


@pytest.mark.asyncio
async def test_runpod_status_parsing_contract():
    """Verify RunPod get_instance_status extracts public IP and SSH port correctly."""
    from terradev_cli.providers.runpod_provider import RunPodProvider

    provider = RunPodProvider({"api_key": "test-key"})

    sample_response = {
        "data": {
            "pod": {
                "id": "pod-12345",
                "name": "test-pod",
                "desiredStatus": "RUNNING",
                "gpuCount": 1,
                "runtime": {
                    "ports": [
                        {
                            "ip": "74.22.1.1",
                            "isIpPublic": True,
                            "privatePort": 22,
                            "publicPort": 22022,
                            "type": "tcp",
                        }
                    ],
                    "gpus": [
                        {
                            "id": "gpu-1",
                            "gpuUtilPercent": 0.0,
                            "memoryUtilPercent": 0.0,
                        }
                    ],
                },
            }
        }
    }

    async def _fake_make_request(*_args, **_kwargs):
        return sample_response

    with patch.object(provider, "_make_request", _fake_make_request):
        status = await provider.get_instance_status("pod-12345")

    assert status["status"] == "running"
    assert status["ip"] == "74.22.1.1"
    assert status["port"] == 22022


@pytest.mark.asyncio
async def test_vastai_quote_shape_contract():
    """Verify Vast.ai quote parsing does not silently drop expected fields."""
    from terradev_cli.providers.vastai_provider import VastAIProvider

    provider = VastAIProvider({"api_key": "test-key"})

    sample_response = {
        "offers": [
            {
                "id": 42,
                "gpu_name": "RTX 4090",
                "num_gpus": 1,
                "dlperf": 100.0,
                "dph_total": 0.45,
                "cuda_max_good": 12.0,
                "inet_up": 100.0,
                "inet_down": 100.0,
                "host_id": 7,
            }
        ]
    }

    captured_url = None

    async def _fake_make_request(method, url, **_kwargs):
        nonlocal captured_url
        captured_url = url
        return sample_response

    with patch.object(provider, "_make_request", _fake_make_request):
        quotes = await provider.get_instance_quotes("RTX4090")

    assert captured_url is not None
    assert "/bundles/" in captured_url
    assert len(quotes) == 1
    assert quotes[0]["provider"] == "vastai"
    assert "price_per_hour" in quotes[0]
    assert quotes[0]["price_per_hour"] == 0.45
