apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lora-serving.fullname" . }}-registry-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lora-serving.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.storage.registryStorage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.registryStorage.size }}
  storageClassName: {{ .Values.storage.registryStorage.storageClass }}
