"""MCP tool schema definitions."""

from typing import Any, List

try:
    from mcp.types import Tool
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False
    Tool = None

TOOLS = []

if Tool is not None:
    TOOLS = [

        Tool(name='moe_deploy', description='Deploy Mixture-of-Experts models with production-ready cluster templates. Auto-applies vLLM cost optimizations (KV cache offloading for up to 9x throughput, MTP speculative decoding for up to 2.8x speed, sleep mode for 18-200x faster restarts). Supports GLM-5, Qwen 3.5, Mistral Large 3, DeepSeek V4, Llama 5. Configures NVLink topology, tensor parallelism, FP8 quantization, vLLM/SGLang backends, and GPU-aware HPA autoscaling.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID (e.g., zai-org/GLM-5-FP8, Qwen/Qwen3.5-397B-A17B)'}, 'gpu_type': {'type': 'string', 'description': 'GPU type for MoE serving', 'enum': ['H100', 'H200', 'H800', 'A100', 'MI300X']}, 'tp_size': {'type': 'integer', 'description': 'Tensor parallelism size (must match NVLink domain)', 'enum': [1, 2, 4, 8], 'default': 8}, 'backend': {'type': 'string', 'description': 'Serving backend', 'enum': ['vllm', 'sglang'], 'default': 'vllm'}, 'quantization': {'type': 'string', 'description': 'Quantization method', 'enum': ['fp8', 'bf16', 'awq', 'gptq'], 'default': 'fp8'}, 'dry_run': {'type': 'boolean', 'description': 'Show deployment plan without executing', 'default': False}}, 'required': ['model_id', 'gpu_type']}),
        Tool(name='train_status', description='List all training jobs and their state (created, running, completed, failed).', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Filter to a specific job ID'}}}),
        Tool(name='train_monitor', description='Real-time GPU monitoring for training jobs. Shows utilization, memory, temperature, power, and cost.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID to monitor'}, 'cost_rate': {'type': 'number', 'description': '$/GPU-hr for cost estimation', 'default': 2.0}}, 'required': ['job_id']}),
        Tool(name='checkpoint_list', description='List all checkpoints for a training job.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID'}}, 'required': ['job_id']}),
        Tool(name='checkpoint_save', description='Manually trigger a checkpoint save for a running training job.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID'}, 'step': {'type': 'integer', 'description': 'Step number'}}, 'required': ['job_id']}),
        Tool(name='train_stop', description='Stop a running training job. Kills training processes on all nodes in parallel.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID to stop'}}, 'required': ['job_id']}),
        Tool(name='train_resume', description='Resume a training job from its latest checkpoint. Rebuilds config with topology revalidation.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID to resume'}, 'checkpoint_id': {'type': 'string', 'description': 'Specific checkpoint to resume from (default: latest)'}}, 'required': ['job_id']}),
        Tool(name='checkpoint_restore', description='Restore a specific checkpoint for a training job.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID'}, 'step': {'type': 'integer', 'description': 'Checkpoint step to restore'}, 'checkpoint_id': {'type': 'string', 'description': 'Checkpoint ID to restore'}}, 'required': ['job_id']}),
        Tool(name='checkpoint_promote', description='Promote a checkpoint to a final model path for serving.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID'}, 'checkpoint_id': {'type': 'string', 'description': 'Checkpoint ID to promote'}, 'dest': {'type': 'string', 'description': 'Destination path (e.g., /models/final)'}}, 'required': ['job_id', 'checkpoint_id', 'dest']}),
        Tool(name='checkpoint_delete', description='Delete a checkpoint.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Job ID'}, 'checkpoint_id': {'type': 'string', 'description': 'Checkpoint ID to delete'}}, 'required': ['job_id', 'checkpoint_id']}),
        Tool(name='lora_list', description='List LoRA adapters loaded on a running vLLM endpoint. Shows base models and hot-loaded fine-tuned adapters.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL (e.g. http://10.0.0.1:8000)'}, 'api_key': {'type': 'string', 'description': 'vLLM API key (if set)'}}, 'required': ['endpoint']}),
        Tool(name='lora_add', description="Hot-load a LoRA adapter onto a running vLLM endpoint. The adapter becomes immediately available as a model name for inference requests. Uses vLLM's fused_moe_lora kernel for 454% higher output tokens/sec on MoE models.", inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL (e.g. http://10.0.0.1:8000)'}, 'name': {'type': 'string', 'description': 'Adapter name (becomes the model name in API requests)'}, 'path': {'type': 'string', 'description': 'Path to adapter weights (local path or HuggingFace ID)'}, 'api_key': {'type': 'string', 'description': 'vLLM API key (if set)'}}, 'required': ['endpoint', 'name', 'path']}),
        Tool(name='lora_remove', description='Hot-unload a LoRA adapter from a running vLLM endpoint. Frees GPU memory for other adapters.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL (e.g. http://10.0.0.1:8000)'}, 'name': {'type': 'string', 'description': 'Adapter name to unload'}, 'api_key': {'type': 'string', 'description': 'vLLM API key (if set)'}}, 'required': ['endpoint', 'name']}),
        Tool(name='training_config_generate', description='Generate a complete training configuration from a declarative spec. Auto-detects framework, sets optimal parallelism, and configures distributed training.', inputSchema={'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Training job name'}, 'framework': {'type': 'string', 'description': 'Training framework', 'enum': ['torchrun', 'deepspeed', 'accelerate', 'megatron'], 'default': 'torchrun'}, 'script': {'type': 'string', 'description': 'Training script path'}, 'nodes': {'type': 'array', 'description': 'Node IPs', 'items': {'type': 'string'}}, 'gpus_per_node': {'type': 'integer', 'description': 'GPUs per node', 'default': 8}, 'from_provision': {'type': 'string', 'description': "Resolve from provision ('latest' or group ID)"}, 'deepspeed_config': {'type': 'object', 'description': 'DeepSpeed config overrides'}, 'script_args': {'type': 'string', 'description': 'Extra script arguments'}}, 'required': ['name', 'script']}),
        Tool(name='training_launch_distributed', description='Full distributed training launch with framework auto-detection, topology validation, and monitoring. Combines preflight + train + monitor in one operation.', inputSchema={'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Job name'}, 'script': {'type': 'string', 'description': 'Training script'}, 'framework': {'type': 'string', 'description': 'Framework', 'enum': ['torchrun', 'deepspeed', 'accelerate', 'megatron'], 'default': 'torchrun'}, 'from_provision': {'type': 'string', 'description': "Resolve nodes from provision ('latest' or group ID)"}, 'nodes': {'type': 'array', 'description': 'Manual node IPs', 'items': {'type': 'string'}}, 'gpus_per_node': {'type': 'integer', 'description': 'GPUs per node', 'default': 8}, 'skip_preflight': {'type': 'boolean', 'description': 'Skip preflight validation', 'default': False}}, 'required': ['name', 'script']}),
        Tool(name='train_snapshot', description='Get complete training monitoring snapshot: GPU metrics (utilization, memory, temp, power), training metrics (loss, grad_norm, lr, throughput), straggler detection, and cost estimate.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Training job ID'}, 'cost_rate': {'type': 'number', 'description': '$/GPU-hr for cost estimation', 'default': 2.0}}, 'required': ['job_id']}),
        Tool(name='train_detect_stragglers', description='Detect straggler nodes in distributed training. Identifies GPUs with significantly lower utilization that slow the whole job.', inputSchema={'type': 'object', 'properties': {'job_id': {'type': 'string', 'description': 'Training job ID'}, 'threshold': {'type': 'number', 'description': 'Straggler threshold (0-1, default 0.7 = 70% of mean)', 'default': 0.7}}, 'required': ['job_id']}),
    ]
