"""MCP tool schema definitions."""

from typing import Any, List

try:
    from mcp.types import Tool
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False
    Tool = None

TOOLS = []

if Tool is not None:
    TOOLS = [
        Tool(name='agent_agentic_serving_configure', description='Configure agentic inference serving settings.', inputSchema={'type': 'object', 'properties': {'engine': {'description': 'Inference engine', 'type': 'string', 'enum': ['vllm', 'sglang'], 'default': 'vllm'}, 'model': {'description': 'model', 'type': 'string', 'default': 'meta-llama/Llama-3.1-8B-Instruct'}, 'tp': {'description': 'Tensor parallel size', 'type': 'integer', 'default': 1}, 'max_model_len': {'description': 'max_model_len', 'type': 'integer', 'default': 32768}, 'gpu_mem': {'description': 'gpu_mem', 'type': 'number', 'default': 0.85}, 'lmcache': {'description': 'Enable LMCache KV offload', 'type': 'boolean', 'default': True}, 'lmcache_backend': {'description': 'lmcache_backend', 'type': 'string', 'enum': ['cpu', 'disk', 'redis'], 'default': 'cpu'}, 'disaggregation': {'description': 'Prefill-decode disaggregation', 'type': 'boolean', 'default': False}}}),
        Tool(name='agent_agentic_serving_helm_values', description='Print Helm values for agentic inference deployment.', inputSchema={'type': 'object', 'properties': {'format': {'description': 'format', 'type': 'string', 'enum': ['json', 'yaml'], 'default': 'yaml'}}}),
        Tool(name='agent_agentic_serving_k8s', description='Print K8s deployment manifests for agentic inference.', inputSchema={'type': 'object', 'properties': {'namespace': {'description': 'K8s namespace', 'type': 'string', 'default': 'inference'}}}),
        Tool(name='agent_agentic_serving_launch_args', description='Print engine launch arguments for copy-paste.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='agent_agentic_serving_lmcache_env', description='Print LMCache environment variables.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='agent_agentic_serving_show_config', description='Show current agentic serving configuration.', inputSchema={'type': 'object', 'properties': {'format': {'description': 'format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}}),
        Tool(name='agent_cost', description='Show real-time cost breakdown for a fleet by tier.', inputSchema={'type': 'object', 'properties': {'fleet_id': {'description': 'Fleet ID', 'type': 'string'}, 'format': {'description': 'format', 'type': 'string', 'enum': ['table', 'json'], 'default': 'table'}}, 'required': ['fleet_id']}),
        Tool(name='agent_deploy', description='Provision a heterogeneous agent fleet across all tiers simultaneously.', inputSchema={'type': 'object', 'properties': {'agents': {'description': 'Number of concurrent agent loops', 'type': 'integer'}, 'model': {'description': 'Model to serve', 'type': 'string', 'default': 'meta-llama/Llama-3.1-70B-Instruct'}, 'reasoning': {'description': 'reasoning', 'type': 'string', 'enum': ['instant', 'thinking'], 'default': 'instant'}, 'topology': {'description': 'Path to agent-fleet.yaml spec file', 'type': 'string'}, 'planner_gpu': {'description': 'Reasoning tier GPU type', 'type': 'string'}, 'planner_count': {'description': 'Reasoning tier instance count', 'type': 'integer'}, 'worker_gpu': {'description': 'Decode tier GPU type', 'type': 'string'}, 'worker_count': {'description': 'Decode tier instance count', 'type': 'integer'}, 'cpu_cores': {'description': 'vCPU count for CPU tools tier', 'type': 'integer', 'default': 48}, 'providers': {'description': 'Cloud providers to use (e.g. runpod vastai)', 'type': 'array', 'items': {'type': 'string'}}, 'max_price': {'description': 'Max price per GPU/hr in USD', 'type': 'number'}, 'dry_run': {'description': 'Show allocation plan without provisioning', 'type': 'boolean', 'default': False}, 'format': {'description': 'format', 'type': 'string', 'enum': ['table', 'json'], 'default': 'table'}}}),
        Tool(name='agent_langchain_create_langgraph', description='Create a LangGraph workflow.', inputSchema={'type': 'object', 'properties': {'graph_name': {'description': 'graph_name', 'type': 'string'}}, 'required': ['graph_name']}),
        Tool(name='agent_langchain_create_pipeline', description='Create an SGLang pipeline.', inputSchema={'type': 'object', 'properties': {'pipeline_name': {'description': 'pipeline_name', 'type': 'string'}}, 'required': ['pipeline_name']}),
        Tool(name='agent_langchain_create_workflow', description='Create a LangChain workflow.', inputSchema={'type': 'object', 'properties': {'workflow_name': {'description': 'workflow_name', 'type': 'string'}}, 'required': ['workflow_name']}),
        Tool(name='agent_langchain_test', description='Test connection to LangChain service.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='agent_langgraph_create_workflow', description='Create a LangGraph workflow.', inputSchema={'type': 'object', 'properties': {'workflow_name': {'description': 'workflow_name', 'type': 'string'}, 'type': {'description': 'Workflow type', 'type': 'string', 'enum': ['orchestrator-worker', 'evaluator-optimizer']}}, 'required': ['workflow_name', 'type']}),
        Tool(name='agent_langgraph_deploy', description='Deploy a workflow.', inputSchema={'type': 'object', 'properties': {'workflow_name': {'description': 'workflow_name', 'type': 'string'}}, 'required': ['workflow_name']}),
        Tool(name='agent_langgraph_status', description='Get workflow status.', inputSchema={'type': 'object', 'properties': {'workflow_id': {'description': 'workflow_id', 'type': 'string'}}, 'required': ['workflow_id']}),
        Tool(name='agent_langgraph_test', description='Test connection to LangGraph service.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='agent_letta_chat', description='Send a message to a Letta agent.', inputSchema={'type': 'object', 'properties': {'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'message': {'description': 'Message to send', 'type': 'string'}, 'environment': {'description': 'Letta environment', 'type': 'string', 'enum': ['cloud', 'local'], 'default': 'cloud'}, 'format': {'description': 'format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}, 'required': ['agent_id', 'message']}),
        Tool(name='agent_letta_create', description='Create a new stateful Letta agent.', inputSchema={'type': 'object', 'properties': {'name': {'description': 'Agent name', 'type': 'string'}, 'model': {'description': 'Model to use', 'type': 'string', 'default': 'openai/gpt-4.1'}, 'human': {'description': 'Human memory block value', 'type': 'string', 'default': ''}, 'persona': {'description': 'Persona memory block value', 'type': 'string', 'default': ''}, 'memory_blocks': {'description': 'JSON list of memory blocks [{"label": ..., "value": ...}]', 'type': 'string', 'default': '[]'}, 'vector_db': {'description': 'Vector DB connection string or JSON config for agent memory', 'type': 'string'}, 'skill': {'description': 'Path to a skill.md to embed as an agent memory block', 'type': 'string'}, 'environment': {'description': 'Letta environment', 'type': 'string', 'enum': ['cloud', 'local'], 'default': 'cloud'}, 'format': {'description': 'format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}, 'required': ['name']}),
        Tool(name='agent_letta_delete', description='Delete a Letta agent.', inputSchema={'type': 'object', 'properties': {'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'environment': {'description': 'Letta environment', 'type': 'string', 'enum': ['cloud', 'local'], 'default': 'cloud'}}, 'required': ['agent_id']}),
        Tool(name='agent_letta_list', description='List Letta agents.', inputSchema={'type': 'object', 'properties': {'environment': {'description': 'Letta environment', 'type': 'string', 'enum': ['cloud', 'local'], 'default': 'cloud'}, 'format': {'description': 'format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}}),
        Tool(name='agent_letta_remember', description='Teach a Letta agent a durable fact.', inputSchema={'type': 'object', 'properties': {'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'text': {'description': 'Fact to remember', 'type': 'string'}, 'label': {'description': 'Memory block label', 'type': 'string', 'default': 'human'}, 'environment': {'description': 'Letta environment', 'type': 'string', 'enum': ['cloud', 'local'], 'default': 'cloud'}}, 'required': ['agent_id', 'text']}),
        Tool(name='agent_letta_status', description='Show the state of a Letta agent.', inputSchema={'type': 'object', 'properties': {'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'environment': {'description': 'Letta environment', 'type': 'string', 'enum': ['cloud', 'local'], 'default': 'cloud'}, 'format': {'description': 'format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}, 'required': ['agent_id']}),
        Tool(name='agent_mem0_add', description='Store a memory in Mem0 for an agent or user.', inputSchema={'type': 'object', 'properties': {'text': {'description': 'Text to remember', 'type': 'string'}, 'user_id': {'description': 'User ID', 'type': 'string'}, 'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'app_id': {'description': 'App ID', 'type': 'string'}, 'run_id': {'description': 'Run/session ID', 'type': 'string'}, 'metadata': {'description': 'JSON metadata', 'type': 'string', 'default': '{}'}, 'no_infer': {'description': 'Skip LLM fact extraction', 'type': 'boolean', 'default': False}, 'format': {'description': 'Output format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}, 'required': ['text', 'user_id']}),
        Tool(name='agent_mem0_configure', description='Configure Mem0 credentials and defaults.', inputSchema={'type': 'object', 'properties': {'api_key': {'description': 'Mem0 API key', 'type': 'string'}, 'mode': {'description': 'Mem0 mode', 'type': 'string', 'enum': ['hosted', 'self_hosted'], 'default': 'hosted'}, 'host': {'description': 'Mem0 Platform host', 'type': 'string', 'default': 'https://api.mem0.ai'}, 'org_id': {'description': 'Mem0 organization ID', 'type': 'string'}, 'project_id': {'description': 'Mem0 project ID', 'type': 'string'}, 'default_user_id': {'description': 'Default user ID', 'type': 'string'}}, 'required': ['api_key']}),
        Tool(name='agent_mem0_delete', description='Delete a memory by ID.', inputSchema={'type': 'object', 'properties': {'memory_id': {'description': 'Memory ID', 'type': 'string'}}, 'required': ['memory_id']}),
        Tool(name='agent_mem0_forget', description='Delete all memories matching an entity scope.', inputSchema={'type': 'object', 'properties': {'user_id': {'description': 'User ID', 'type': 'string'}, 'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'app_id': {'description': 'App ID', 'type': 'string'}, 'run_id': {'description': 'Run/session ID', 'type': 'string'}, 'yes': {'description': 'Skip confirmation', 'type': 'boolean', 'default': False}}, 'required': ['user_id']}),
        Tool(name='agent_mem0_get', description='Get a single memory by ID.', inputSchema={'type': 'object', 'properties': {'memory_id': {'description': 'Memory ID', 'type': 'string'}, 'format': {'description': 'Output format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}, 'required': ['memory_id']}),
        Tool(name='agent_mem0_list', description='List memories for an entity scope.', inputSchema={'type': 'object', 'properties': {'user_id': {'description': 'User ID', 'type': 'string'}, 'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'app_id': {'description': 'App ID', 'type': 'string'}, 'run_id': {'description': 'Run/session ID', 'type': 'string'}, 'page': {'description': 'Page number', 'type': 'integer', 'default': 1}, 'page_size': {'description': 'Results per page', 'type': 'integer', 'default': 50}, 'format': {'description': 'Output format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}, 'required': ['user_id']}),
        Tool(name='agent_mem0_search', description='Search agent/user memories.', inputSchema={'type': 'object', 'properties': {'query': {'description': 'Search query', 'type': 'string'}, 'user_id': {'description': 'User ID', 'type': 'string'}, 'agent_id': {'description': 'Agent ID', 'type': 'string'}, 'app_id': {'description': 'App ID', 'type': 'string'}, 'run_id': {'description': 'Run/session ID', 'type': 'string'}, 'top_k': {'description': 'Number of results', 'type': 'integer', 'default': 10}, 'format': {'description': 'Output format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}, 'required': ['query', 'user_id']}),
        Tool(name='agent_mem0_test', description='Test connection to Mem0.', inputSchema={'type': 'object', 'properties': {'format': {'description': 'Output format', 'type': 'string', 'enum': ['json', 'text'], 'default': 'text'}}}),
        Tool(name='agent_mem0_update', description='Update a memory by ID.', inputSchema={'type': 'object', 'properties': {'memory_id': {'description': 'Memory ID', 'type': 'string'}, 'text': {'description': 'Updated memory text', 'type': 'string'}, 'metadata': {'description': 'JSON metadata', 'type': 'string', 'default': '{}'}}, 'required': ['memory_id']}),
        Tool(name='agent_list', description='List all known agent fleets.', inputSchema={'type': 'object', 'properties': {'format': {'description': 'format', 'type': 'string', 'enum': ['table', 'json'], 'default': 'table'}}}),
        Tool(name='agent_plan', description='Plan a heterogeneous agent fleet without provisioning.', inputSchema={'type': 'object', 'properties': {'agents': {'description': 'Number of concurrent agent loops to provision for', 'type': 'integer'}, 'model': {'description': 'Model to serve across the fleet', 'type': 'string', 'default': 'meta-llama/Llama-3.1-70B-Instruct'}, 'reasoning': {'description': 'Reasoning mode: instant (faster) or thinking (extended CoT, 45-67% more output tokens)', 'type': 'string', 'enum': ['instant', 'thinking'], 'default': 'instant'}, 'planner_gpu': {'description': 'Override reasoning tier GPU type (e.g. H100_SXM)', 'type': 'string'}, 'planner_count': {'description': 'Override reasoning tier instance count', 'type': 'integer'}, 'worker_gpu': {'description': 'Override decode tier GPU type (e.g. A100_SXM_80)', 'type': 'string'}, 'worker_count': {'description': 'Override decode tier instance count', 'type': 'integer'}, 'cpu_cores': {'description': 'vCPU count for CPU tools tier instances', 'type': 'integer', 'default': 48}, 'format': {'description': 'Output format', 'type': 'string', 'enum': ['table', 'json'], 'default': 'table'}}, 'required': ['agents']}),
        Tool(name='agent_scale', description='Scale a single fleet tier up or down without affecting other tiers.', inputSchema={'type': 'object', 'properties': {'fleet_id': {'description': 'Fleet ID', 'type': 'string'}, 'tier': {'description': 'Tier to scale', 'type': 'string', 'enum': ['reasoning', 'decode', 'cpu_tools']}, 'count': {'description': 'New instance count for this tier', 'type': 'integer'}, 'providers': {'description': 'Providers to use for scale-out instances', 'type': 'array', 'items': {'type': 'string'}}}, 'required': ['fleet_id', 'tier', 'count']}),
        Tool(name='agent_skill_attach', description='Attach a skill.md to a Letta agent as a durable memory block.', inputSchema={'type': 'object', 'properties': {'agent_id': {'description': 'Letta agent ID', 'type': 'string'}, 'skill': {'description': 'Path to skill.md', 'type': 'string'}, 'label': {'description': 'Memory block label', 'type': 'string', 'default': 'skill'}, 'environment': {'description': 'Letta environment', 'type': 'string', 'enum': ['cloud', 'local'], 'default': 'cloud'}}, 'required': ['agent_id', 'skill']}),
        Tool(name='agent_skill_init', description='Create a skill.md template for an agent.', inputSchema={'type': 'object', 'properties': {'name': {'description': 'Skill name', 'type': 'string'}, 'output': {'description': 'Output path (default: <name>.skill.md)', 'type': 'string'}, 'description': {'description': 'Short description', 'type': 'string', 'default': ''}, 'tools': {'description': 'Comma-separated tool names', 'type': 'string', 'default': ''}}, 'required': ['name']}),
        Tool(name='agent_status', description='Show live status of a fleet — tier health, KV hit rate, queue depth, cost.', inputSchema={'type': 'object', 'properties': {'fleet_id': {'description': "Fleet ID returned by 'terradev agent deploy'", 'type': 'string'}, 'format': {'description': 'format', 'type': 'string', 'enum': ['table', 'json'], 'default': 'table'}}, 'required': ['fleet_id']}),
        Tool(name='agent_teardown', description='Terminate all fleet instances and remove fleet state.', inputSchema={'type': 'object', 'properties': {'fleet_id': {'description': 'Fleet ID to destroy', 'type': 'string'}, 'yes': {'description': 'Skip confirmation prompt', 'type': 'boolean', 'default': False}}, 'required': ['fleet_id']}),
        Tool(name='agent_vector_db_down', description='Teardown a vector database provisioned for an agent fleet.', inputSchema={'type': 'object', 'properties': {'name': {'description': 'Vector DB name', 'type': 'string', 'default': 'agent-memory'}, 'adapter': {'description': 'Vector DB adapter', 'type': 'string', 'enum': ['qdrant', 'weaviate'], 'default': 'qdrant'}, 'config': {'description': 'JSON adapter config', 'type': 'string', 'default': '{}'}, 'manifest': {'description': 'Path to universal manifest', 'type': 'string'}}}),
        Tool(name='agent_vector_db_up', description='Provision a vector database for an agent fleet.', inputSchema={'type': 'object', 'properties': {'name': {'description': 'Vector DB name', 'type': 'string', 'default': 'agent-memory'}, 'adapter': {'description': 'Vector DB adapter', 'type': 'string', 'enum': ['qdrant', 'weaviate'], 'default': 'qdrant'}, 'config': {'description': 'JSON adapter config', 'type': 'string', 'default': '{}'}, 'manifest': {'description': 'Path to universal manifest', 'type': 'string'}}}),
    ]