"""MCP tool schema definitions."""

from typing import Any, List

try:
    from mcp.types import Tool
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False
    Tool = None

TOOLS = []

if Tool is not None:
    TOOLS = [

        Tool(name='local_scan', description='Scan local machine and network for available GPU devices. Returns total VRAM pool for local-first provisioning.', inputSchema={'type': 'object', 'properties': {}, 'required': []}),
        Tool(name='status', description='View all instances and costs with Terraform state optimization', inputSchema={'type': 'object', 'properties': {'live': {'type': 'boolean', 'description': 'Show live status vs cached Terraform state', 'default': False}, 'use_terraform_state': {'type': 'boolean', 'description': 'Use Terraform state for faster queries', 'default': True}, 'state_file': {'type': 'string', 'description': 'Path to Terraform state file (optional)'}}}),
        Tool(name='manage_instance', description='Manage GPU instances (stop/start/terminate)', inputSchema={'type': 'object', 'properties': {'instance_id': {'type': 'string', 'description': 'Instance ID'}, 'action': {'type': 'string', 'description': 'Action to perform', 'enum': ['stop', 'start', 'terminate']}}, 'required': ['instance_id', 'action']}),
        Tool(name='analytics', description='Get cost analytics', inputSchema={'type': 'object', 'properties': {'days': {'type': 'integer', 'description': 'Number of days to analyze', 'minimum': 1, 'default': 30}}}),
        Tool(name='optimize', description='Find cheaper alternatives for running instances', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='setup_provider', description='Get setup instructions for a provider', inputSchema={'type': 'object', 'properties': {'provider': {'type': 'string', 'description': 'Provider name', 'enum': ['runpod', 'aws', 'vastai', 'gcp', 'azure', 'lambda', 'coreweave', 'tensordock', 'oracle', 'crusoe', 'digitalocean', 'hyperstack', 'alibaba', 'ovhcloud', 'fluidstack', 'hetzner', 'siliconflow', 'latitude', 'huggingface', 'baseten', 'inferx']}, 'quick': {'type': 'boolean', 'description': 'Quick setup instructions', 'default': True}}, 'required': ['provider']}),
        Tool(name='configure_provider', description='Configure provider credentials', inputSchema={'type': 'object', 'properties': {'provider': {'type': 'string', 'description': 'Provider to configure', 'enum': ['runpod', 'aws', 'vastai', 'gcp', 'azure', 'lambda', 'coreweave', 'tensordock', 'oracle', 'crusoe', 'digitalocean', 'hyperstack', 'alibaba', 'ovhcloud', 'fluidstack', 'hetzner', 'siliconflow', 'latitude', 'huggingface', 'baseten', 'inferx']}}, 'required': ['provider']}),
        Tool(name='train', description="Launch distributed training on provisioned GPU nodes. Supports torchrun, deepspeed, accelerate, and megatron. Use from_provision='latest' to auto-resolve node IPs from your last provision command.", inputSchema={'type': 'object', 'properties': {'script': {'type': 'string', 'description': 'Training script path (e.g., train.py)'}, 'framework': {'type': 'string', 'description': 'Training framework', 'enum': ['torchrun', 'deepspeed', 'accelerate', 'megatron'], 'default': 'torchrun'}, 'from_provision': {'type': 'string', 'description': "Resolve nodes from provision. Use 'latest' or a parallel_group_id."}, 'nodes': {'type': 'array', 'description': 'Manual node IPs', 'items': {'type': 'string'}}, 'gpus_per_node': {'type': 'integer', 'description': 'GPUs per node', 'default': 8}, 'script_args': {'type': 'string', 'description': 'Extra args for training script'}}, 'required': ['script']}),
        Tool(name='preflight', description='Pre-training validation: GPU availability, NCCL, RDMA, drivers across all nodes.', inputSchema={'type': 'object', 'properties': {'nodes': {'type': 'array', 'description': 'Node IPs to validate', 'items': {'type': 'string'}}, 'from_provision': {'type': 'string', 'description': "Resolve nodes from provision. 'latest' or a group ID."}}}),
        Tool(name='stage', description='Compress, chunk, checksum, and position datasets near compute. Supports local paths, S3/GCS URIs, HTTP URLs, and HuggingFace dataset names. Returns staging plan with agent recommendations.', inputSchema={'type': 'object', 'properties': {'dataset': {'type': 'string', 'description': 'Dataset path, S3 URI, GCS URI, HTTP URL, or HuggingFace name'}, 'target_regions': {'type': 'string', 'description': 'Comma-separated target regions'}, 'compression': {'type': 'string', 'description': 'Compression algorithm', 'enum': ['auto', 'zstd', 'gzip', 'none'], 'default': 'auto'}, 'plan_only': {'type': 'boolean', 'description': 'Show staging plan without executing', 'default': False}}, 'required': ['dataset']}),
        Tool(name='up', description='CLI-native provisioning with manifest cache and drift detection. Use --fix-drift to detect and auto-fix drifted infrastructure.', inputSchema={'type': 'object', 'properties': {'job': {'type': 'string', 'description': 'Job name for manifest tracking'}, 'gpu_type': {'type': 'string', 'description': 'GPU type', 'default': 'A100'}, 'gpu_count': {'type': 'integer', 'description': 'Number of GPUs', 'default': 1}, 'hours': {'type': 'number', 'description': 'Estimated runtime in hours', 'default': 1.0}, 'budget': {'type': 'number', 'description': 'Budget constraint ($/hr)'}, 'region': {'type': 'string', 'description': 'Preferred region'}, 'ttl': {'type': 'string', 'description': 'Time to live for nodes', 'default': '1h'}, 'fix_drift': {'type': 'boolean', 'description': 'Detect and fix drift automatically', 'default': False}}, 'required': ['job']}),
        Tool(name='rollback', description='Explicit versioned rollback. Format: job@version (e.g., llama3@v3).', inputSchema={'type': 'object', 'properties': {'job_version': {'type': 'string', 'description': 'Job@version string (e.g., llama3@v3)'}}, 'required': ['job_version']}),
        Tool(name='manifests', description='List cached manifests and versions for jobs.', inputSchema={'type': 'object', 'properties': {'job': {'type': 'string', 'description': 'Show versions for specific job (optional)'}}}),
        Tool(name='smart_deploy', description='AI-ranked deployment options with confidence/risk scoring. Returns recommendations with cost estimates and requires_confirmation for execution.', inputSchema={'type': 'object', 'properties': {'image': {'type': 'string', 'description': 'Container image'}, 'workload': {'type': 'string', 'description': 'Workload type', 'enum': ['training', 'inference', 'batch']}, 'gpu_type': {'type': 'string', 'description': 'GPU type'}, 'budget': {'type': 'number', 'description': 'Max $/hr budget'}, 'option': {'type': 'integer', 'description': 'Execute a specific recommended option by index'}}, 'required': ['image', 'workload']}),
        Tool(name='run_workflow', description='Run a declarative YAML workflow that chains multiple Terradev commands (provision → preflight → train → monitor → checkpoint). Returns step-by-step execution status with cost estimates and confirmation gates for expensive operations.', inputSchema={'type': 'object', 'properties': {'workflow': {'type': 'string', 'description': 'Workflow YAML path or inline YAML string'}, 'dry_run': {'type': 'boolean', 'description': 'Show execution plan without running', 'default': False}, 'template': {'type': 'string', 'description': 'Use built-in template', 'enum': ['finetune-llama', 'inference-deploy', 'benchmark-gpu', 'cost-optimize']}}}),
        Tool(name='active_context', description='Get current Terradev state: running training jobs, active instances, spend-to-date, alerts. Call this on session start to resume context from previous sessions.', inputSchema={'type': 'object', 'properties': {}}),
    ]
