"""MCP tool schema definitions."""

from typing import Any, List

try:
    from mcp.types import Tool
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False
    Tool = None

TOOLS = []

if Tool is not None:
    TOOLS = [

        Tool(name='inferx_deploy', description='Deploy model to InferX serverless platform using Terraform for infrastructure as code', inputSchema={'type': 'object', 'properties': {'model': {'type': 'string', 'description': 'Model ID (e.g., meta-llama/Llama-2-7b-hf)'}, 'gpu_type': {'type': 'string', 'description': 'GPU type for inference', 'enum': ['H100', 'A100', 'A10G', 'L40S', 'L4', 'T4', 'RTX4090', 'RTX3090', 'V100']}, 'endpoint_name': {'type': 'string', 'description': 'Custom endpoint name (optional)'}, 'use_terraform': {'type': 'boolean', 'description': 'Use Terraform for infrastructure as code', 'default': True}}, 'required': ['model', 'gpu_type']}),
        Tool(name='inferx_status', description='Check InferX endpoint status', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='inferx_list', description='List deployed InferX models', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='inferx_optimize', description='Get cost analysis for inference endpoints', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='infer_route', description='Semantic-aware inference routing. Analyzes query content across 6 signal dimensions (modality, complexity, domain, language, safety, keywords), applies NUMA-aware endpoint scoring, and selects the optimal inference endpoint. Uses Terraform-style DAG parallel execution for signal extraction.', inputSchema={'type': 'object', 'properties': {'model': {'type': 'string', 'description': 'Filter by model name (e.g., llama-3-70b, deepseek-coder-33b)'}, 'strategy': {'type': 'string', 'description': 'Routing strategy', 'enum': ['latency', 'cost', 'score'], 'default': 'latency'}, 'measure': {'type': 'boolean', 'description': 'Run fresh latency measurements (HTTP TTFB / WebPageTest) before routing', 'default': False}}}),
        Tool(name='infer_route_disagg', description='Disaggregated Prefill/Decode routing (DistServe architecture). Splits LLM inference into compute-bound prefill phase (routed to FLOPS-optimized GPUs like H100 SXM) and memory-bound decode phase (routed to bandwidth-optimized GPUs like MI300X). Tracks KV cache handoffs between endpoint pairs.', inputSchema={'type': 'object', 'properties': {'model': {'type': 'string', 'description': 'Model name for disaggregated pair selection (e.g., llama-3-70b)'}, 'check_health': {'type': 'boolean', 'description': 'Run health probes before selecting pairs', 'default': True}}, 'required': ['model']}),
        Tool(name='infer_status', description='Show inference endpoint health, latency, failover status, and disaggregated phase assignments (PREFILL/DECODE/MIXED). Includes KV cache warm status per endpoint.', inputSchema={'type': 'object', 'properties': {'check': {'type': 'boolean', 'description': 'Run live health probes before showing status', 'default': False}}}),
        Tool(name='infer_failover', description='Run health checks and auto-failover for inference endpoints. If a primary endpoint is unhealthy and has a backup configured, traffic automatically shifts to the backup provider.', inputSchema={'type': 'object', 'properties': {'dry_run': {'type': 'boolean', 'description': 'Show what would happen without executing failover', 'default': False}}}),
        Tool(name='gpu_topology', description='GPU NUMA topology report with intra-GPU XCD (Accelerated Compute Die) awareness. Models MI300X (8 XCDs, 192GB HBM3), MI300A (6 XCDs, 128GB), H200 (unified 141GB HBM3e), H100 (80GB). Reports PCIe locality (PIX/PXB/PHB/SYS), GPU-NIC pairing, SR-IOV VF status, and generates XCD-aware NCCL/AITER environment variables.', inputSchema={'type': 'object', 'properties': {'gpu_arch': {'type': 'string', 'description': 'Filter by GPU architecture', 'enum': ['mi300x', 'mi300a', 'h200', 'h100', 'a100', 'auto']}, 'generate_env': {'type': 'boolean', 'description': 'Generate XCD-aware NCCL/AITER/CK env vars for optimal attention kernel performance', 'default': True}}}),
        Tool(name='infer_deploy', description='Deploy an inference endpoint with auto-scaling, idle shutdown, and cost optimization. Returns estimated cost and requires_confirmation for expensive deployments.', inputSchema={'type': 'object', 'properties': {'model_path': {'type': 'string', 'description': 'Model path or HuggingFace model ID'}, 'name': {'type': 'string', 'description': 'Endpoint name'}, 'provider': {'type': 'string', 'description': 'Provider for deployment', 'enum': ['runpod', 'vastai', 'lambda', 'aws', 'gcp', 'coreweave', 'alibaba', 'ovhcloud', 'fluidstack', 'hetzner', 'siliconflow', 'latitude']}, 'gpu_type': {'type': 'string', 'description': 'GPU type', 'enum': ['H100', 'H200', 'H800', 'A100', 'A10G', 'L40S', 'L4', 'T4', 'V100S', 'A6000', 'MI300X']}, 'min_workers': {'type': 'integer', 'description': 'Minimum workers', 'default': 0}, 'max_workers': {'type': 'integer', 'description': 'Maximum workers', 'default': 3}, 'idle_timeout': {'type': 'integer', 'description': 'Idle timeout in seconds', 'default': 300}, 'cost_optimize': {'type': 'boolean', 'description': 'Enable cost optimization', 'default': True}, 'dry_run': {'type': 'boolean', 'description': 'Show deployment plan without deploying', 'default': False}}, 'required': ['model_path', 'name']}),
        Tool(name='inferx_configure', description='Configure InferX serverless platform credentials.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'InferX API key'}, 'endpoint': {'type': 'string', 'description': 'InferX API endpoint', 'default': 'https://api.inferx.net'}, 'region': {'type': 'string', 'description': 'Region', 'default': 'us-west-2'}}, 'required': ['api_key']}),
        Tool(name='inferx_delete', description='Delete an InferX model deployment.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'Model deployment ID to delete'}}, 'required': ['model_id']}),
        Tool(name='inferx_usage', description='Get InferX account usage statistics: requests, cost, GPU hours, latency.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='inferx_quote', description='Get InferX pricing quotes for a GPU type.', inputSchema={'type': 'object', 'properties': {'gpu_type': {'type': 'string', 'description': 'GPU type to quote', 'default': 'A100'}, 'region': {'type': 'string', 'description': 'Region for quote'}}}),
        Tool(name='vllm_start', description='Start a vLLM inference server on a remote instance via SSH/systemd. Supports Multi-LoRA, Sleep Mode, KV Offloading, Speculative Decoding.', inputSchema={'type': 'object', 'properties': {'instance_ip': {'type': 'string', 'description': 'Target instance IP'}, 'model': {'type': 'string', 'description': 'HuggingFace model ID'}, 'port': {'type': 'integer', 'description': 'Server port', 'default': 8000}, 'tp_size': {'type': 'integer', 'description': 'Tensor parallel size', 'default': 1}, 'gpu_memory_utilization': {'type': 'number', 'description': 'GPU memory fraction', 'default': 0.9}, 'ssh_user': {'type': 'string', 'description': 'SSH user', 'default': 'root'}, 'ssh_key': {'type': 'string', 'description': 'Path to SSH private key'}, 'api_key': {'type': 'string', 'description': 'vLLM API key to set'}}, 'required': ['instance_ip', 'model']}),
        Tool(name='vllm_stop', description='Stop a vLLM server on a remote instance.', inputSchema={'type': 'object', 'properties': {'instance_ip': {'type': 'string', 'description': 'Target instance IP'}, 'ssh_user': {'type': 'string', 'description': 'SSH user', 'default': 'root'}, 'ssh_key': {'type': 'string', 'description': 'Path to SSH private key'}}, 'required': ['instance_ip']}),
        Tool(name='vllm_inference', description='Test inference against a running vLLM endpoint (completions or chat).', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL (e.g. http://10.0.0.1:8000)'}, 'prompt': {'type': 'string', 'description': 'Prompt text (for completions mode)'}, 'messages': {'type': 'array', 'description': 'Chat messages array (for chat mode)', 'items': {'type': 'object'}}, 'model': {'type': 'string', 'description': 'Model name to use'}, 'max_tokens': {'type': 'integer', 'description': 'Max tokens to generate', 'default': 100}, 'api_key': {'type': 'string', 'description': 'vLLM API key'}}, 'required': ['endpoint', 'model']}),
        Tool(name='vllm_info', description='Get vLLM server info: loaded models, config, and health status.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL (e.g. http://10.0.0.1:8000)'}, 'api_key': {'type': 'string', 'description': 'vLLM API key'}}, 'required': ['endpoint']}),
        Tool(name='vllm_sleep', description='Put a vLLM server to sleep. Level 1: offload to CPU (fast wake). Level 2: discard weights (minimal RAM).', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL'}, 'level': {'type': 'integer', 'description': 'Sleep level (1=CPU offload, 2=discard)', 'default': 1, 'enum': [1, 2]}}, 'required': ['endpoint']}),
        Tool(name='vllm_wake', description='Wake a sleeping vLLM server. For Level 2 sleep, also reloads weights and resets prefix cache.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL'}, 'sleep_level': {'type': 'integer', 'description': 'The sleep level the server is at (affects wake procedure)', 'default': 1}}, 'required': ['endpoint']}),
        Tool(name='sglang', description='Complete SGLang optimization stack with workload-specific auto-tuning for 7 workload types: agentic chat, batch inference, low latency, MoE models, PD disaggregated, structured output, and RAG.', inputSchema={'type': 'object', 'properties': {'action': {'type': 'string', 'description': 'SGLang action to perform', 'enum': ['optimize', 'detect', 'router', 'install', 'start', 'stop', 'inference', 'metrics', 'test']}, 'model_path': {'type': 'string', 'description': 'HuggingFace model ID or path'}, 'workload_type': {'type': 'string', 'description': 'Workload type for optimization', 'enum': ['agentic_chat', 'batch_inference', 'low_latency', 'moe_model', 'pd_disaggregated', 'structured_output', 'rag_workload']}, 'user_description': {'type': 'string', 'description': 'Natural language description of workload'}, 'host': {'type': 'string', 'description': 'Server host', 'default': '0.0.0.0'}, 'port': {'type': 'integer', 'description': 'Server port', 'default': 8000}, 'dry_run': {'type': 'boolean', 'description': 'Show optimization plan without launching', 'default': False}, 'dp_size': {'type': 'integer', 'description': 'Data parallel size for multi-replica', 'default': 8}, 'instance_ip': {'type': 'string', 'description': 'Remote instance IP for installation/deployment'}, 'ssh_user': {'type': 'string', 'description': 'SSH user for remote operations', 'default': 'root'}, 'ssh_key': {'type': 'string', 'description': 'Path to SSH private key'}, 'endpoint': {'type': 'string', 'description': 'SGLang endpoint URL for inference/metrics'}, 'prompt': {'type': 'string', 'description': 'Prompt text for inference testing'}, 'messages': {'type': 'array', 'description': 'Chat messages array', 'items': {'type': 'object'}}, 'max_tokens': {'type': 'integer', 'description': 'Max tokens to generate', 'default': 100}, 'api_key': {'type': 'string', 'description': 'API key for inference'}, 'tp_size': {'type': 'integer', 'description': 'Tensor parallel size', 'default': 1}, 'enable_expert_parallel': {'type': 'boolean', 'description': 'Enable MoE Expert Parallelism', 'default': False}}, 'required': ['action']}),
        Tool(name='sglang_start', description="[DEPRECATED] Use sglang action='start' instead. Start an SGLang inference server on a remote instance.", inputSchema={'type': 'object', 'properties': {'instance_ip': {'type': 'string', 'description': 'Target instance IP'}, 'model': {'type': 'string', 'description': 'HuggingFace model ID'}, 'port': {'type': 'integer', 'description': 'Server port', 'default': 8000}, 'tp_size': {'type': 'integer', 'description': 'Tensor parallel size', 'default': 1}, 'dp_size': {'type': 'integer', 'description': 'Data parallel size', 'default': 8}, 'enable_expert_parallel': {'type': 'boolean', 'description': 'Enable MoE Expert Parallelism', 'default': False}, 'ssh_user': {'type': 'string', 'description': 'SSH user', 'default': 'root'}, 'ssh_key': {'type': 'string', 'description': 'Path to SSH private key'}}, 'required': ['instance_ip', 'model']}),
        Tool(name='sglang_stop', description="[DEPRECATED] Use sglang action='stop' instead. Stop an SGLang server on a remote instance.", inputSchema={'type': 'object', 'properties': {'instance_ip': {'type': 'string', 'description': 'Target instance IP'}, 'ssh_user': {'type': 'string', 'description': 'SSH user', 'default': 'root'}, 'ssh_key': {'type': 'string', 'description': 'Path to SSH private key'}}, 'required': ['instance_ip']}),
        Tool(name='sglang_inference', description="[DEPRECATED] Use sglang action='inference' instead. Test inference against a running SGLang endpoint.", inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'SGLang endpoint URL (e.g. http://10.0.0.1:8000)'}, 'prompt': {'type': 'string', 'description': 'Prompt text (for completions mode)'}, 'messages': {'type': 'array', 'description': 'Chat messages array (for chat mode)', 'items': {'type': 'object'}}, 'model': {'type': 'string', 'description': 'Model name to use'}, 'max_tokens': {'type': 'integer', 'description': 'Max tokens to generate', 'default': 100}, 'api_key': {'type': 'string', 'description': 'API key'}}, 'required': ['endpoint', 'model']}),
        Tool(name='sglang_metrics', description="[DEPRECATED] Use sglang action='metrics' instead. Get SGLang server metrics from the Prometheus endpoint.", inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'SGLang endpoint URL (e.g. http://10.0.0.1:8000)'}}, 'required': ['endpoint']}),
        Tool(name='ollama_list', description='List models available on an Ollama server.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'Ollama endpoint URL', 'default': 'http://localhost:11434'}}, 'required': []}),
        Tool(name='ollama_pull', description='Pull a model to an Ollama server on a remote instance.', inputSchema={'type': 'object', 'properties': {'model': {'type': 'string', 'description': 'Model name (e.g. llama3.2, deepseek-r1, codellama)'}, 'instance_ip': {'type': 'string', 'description': 'Target instance IP'}, 'ssh_user': {'type': 'string', 'description': 'SSH user', 'default': 'root'}, 'ssh_key': {'type': 'string', 'description': 'Path to SSH private key'}}, 'required': ['model', 'instance_ip']}),
        Tool(name='ollama_generate', description='Generate text using an Ollama model (non-chat completions).', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'Ollama endpoint URL', 'default': 'http://localhost:11434'}, 'model': {'type': 'string', 'description': 'Model name'}, 'prompt': {'type': 'string', 'description': 'Prompt text'}}, 'required': ['model', 'prompt']}),
        Tool(name='ollama_chat', description='Chat with an Ollama model using the chat/completions API.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'Ollama endpoint URL', 'default': 'http://localhost:11434'}, 'model': {'type': 'string', 'description': 'Model name'}, 'messages': {'type': 'array', 'description': 'Chat messages [{role, content}]', 'items': {'type': 'object'}}}, 'required': ['model', 'messages']}),
        Tool(name='ollama_model_info', description='Get detailed information about an Ollama model (parameters, template, license).', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'Ollama endpoint URL', 'default': 'http://localhost:11434'}, 'model': {'type': 'string', 'description': 'Model name'}}, 'required': ['model']}),
        Tool(name='vllm_auto_optimize', description='Automatically optimize vLLM configuration by analyzing workload patterns. Selects optimal settings for the 6 critical knobs based on live endpoint metrics or sample request files.', inputSchema={'type': 'object', 'properties': {'model': {'type': 'string', 'description': 'Model name'}, 'endpoint': {'type': 'string', 'description': 'Running vLLM endpoint to analyze (e.g. http://localhost:8000)'}, 'gpu_count': {'type': 'integer', 'description': 'Number of GPUs available', 'default': 1}, 'output': {'type': 'string', 'enum': ['config', 'args', 'helm'], 'default': 'config'}}, 'required': ['model']}),
        Tool(name='vllm_analyze', description="Analyze a running vLLM server's workload and return specific optimization recommendations with before/after comparisons.", inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL (e.g. http://localhost:8000)'}, 'duration': {'type': 'integer', 'description': 'Analysis duration in seconds', 'default': 60}}, 'required': ['endpoint']}),
        Tool(name='vllm_benchmark', description='Benchmark a vLLM endpoint with concurrent requests. Returns throughput (req/s), success rate, and total latency.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'vLLM endpoint URL'}, 'concurrent': {'type': 'integer', 'description': 'Number of concurrent requests', 'default': 1}, 'prompt': {'type': 'string', 'description': 'Test prompt', 'default': 'Explain quantum computing in simple terms.'}, 'api_key': {'type': 'string', 'description': 'vLLM API key (if auth enabled)'}}, 'required': ['endpoint']}),
        Tool(name='ollama_ps', description='List currently running Ollama models.', inputSchema={'type': 'object', 'properties': {'endpoint': {'type': 'string', 'description': 'Ollama endpoint URL', 'default': 'http://localhost:11434'}}, 'required': []}),
    ]
