"""MCP tool schema definitions."""

from typing import Any, List

try:
    from mcp.types import Tool
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False
    Tool = None

TOOLS = []

if Tool is not None:
    TOOLS = [

        Tool(name='k8s_create', description='Create Kubernetes cluster with GPU nodes using Terraform for optimal multi-cloud deployment', inputSchema={'type': 'object', 'properties': {'cluster_name': {'type': 'string', 'description': 'Name of the cluster'}, 'gpu_type': {'type': 'string', 'description': 'GPU type for nodes', 'enum': ['H100', 'A100', 'A10G', 'L40S', 'L4', 'T4', 'RTX4090', 'RTX3090', 'V100']}, 'count': {'type': 'integer', 'description': 'Number of GPU nodes', 'minimum': 1, 'default': 1}, 'multi_cloud': {'type': 'boolean', 'description': 'Use multi-cloud node pools for resilience', 'default': False}, 'prefer_spot': {'type': 'boolean', 'description': 'Prefer spot instances for cost savings', 'default': True}, 'use_terraform': {'type': 'boolean', 'description': 'Use Terraform for infrastructure as code', 'default': True}}, 'required': ['cluster_name', 'gpu_type']}),
        Tool(name='k8s_list', description='List Kubernetes clusters', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='k8s_info', description='Get information about a specific cluster', inputSchema={'type': 'object', 'properties': {'cluster_name': {'type': 'string', 'description': 'Name of the cluster'}}, 'required': ['cluster_name']}),
        Tool(name='k8s_destroy', description='Destroy a Kubernetes cluster', inputSchema={'type': 'object', 'properties': {'cluster_name': {'type': 'string', 'description': 'Name of the cluster to destroy'}}, 'required': ['cluster_name']}),
        Tool(name='helm_generate', description='Generate Helm charts from workload specifications.', inputSchema={'type': 'object', 'properties': {'workload': {'type': 'string', 'description': 'Workload type', 'enum': ['training', 'inference', 'batch']}, 'image': {'type': 'string', 'description': 'Container image'}, 'gpu_type': {'type': 'string', 'description': 'GPU type'}, 'replicas': {'type': 'integer', 'description': 'Number of replicas', 'default': 1}}, 'required': ['workload', 'image']}),
        Tool(name='kserve_generate_yaml', description='Generate a GPU-aware KServe InferenceService YAML manifest with NUMA pinning, resource limits derived from model size and VRAM, and topology hints.', inputSchema={'type': 'object', 'properties': {'model_name': {'type': 'string', 'description': 'Model name for the InferenceService'}, 'model_uri': {'type': 'string', 'description': 'Model storage URI (e.g. s3://bucket/model or gs://bucket/model)'}, 'gpu_type': {'type': 'string', 'description': 'GPU type (e.g. A100, H100)'}, 'gpu_count': {'type': 'integer', 'description': 'Number of GPUs', 'default': 1}, 'namespace': {'type': 'string', 'description': 'Kubernetes namespace', 'default': 'default'}, 'runtime': {'type': 'string', 'description': 'Serving runtime', 'enum': ['vllm', 'triton', 'huggingface'], 'default': 'vllm'}, 'min_replicas': {'type': 'integer', 'description': 'Min replicas for autoscaling', 'default': 1}, 'max_replicas': {'type': 'integer', 'description': 'Max replicas for autoscaling', 'default': 3}}, 'required': ['model_name', 'model_uri', 'gpu_type']}),
        Tool(name='kserve_list', description='List KServe InferenceServices in a Kubernetes namespace.', inputSchema={'type': 'object', 'properties': {'namespace': {'type': 'string', 'description': 'Kubernetes namespace', 'default': 'default'}}, 'required': []}),
        Tool(name='kserve_status', description='Get detailed status of a KServe InferenceService including readiness, traffic split, and URL.', inputSchema={'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'InferenceService name'}, 'namespace': {'type': 'string', 'description': 'Kubernetes namespace', 'default': 'default'}}, 'required': ['name']}),
        Tool(name='k8s_gpu_operator_install', description='Install NVIDIA GPU Operator on a Kubernetes cluster. Configures driver containers, device plugin, DCGM exporter, and GPU Feature Discovery.', inputSchema={'type': 'object', 'properties': {'cluster_name': {'type': 'string', 'description': 'Target cluster name'}, 'driver_version': {'type': 'string', 'description': 'NVIDIA driver version (default: auto-detect)'}, 'namespace': {'type': 'string', 'description': 'Install namespace', 'default': 'gpu-operator'}}, 'required': ['cluster_name']}),
        Tool(name='k8s_device_plugin', description='Configure Kubernetes GPU device plugin settings: time-slicing, MIG strategy, and resource naming.', inputSchema={'type': 'object', 'properties': {'cluster_name': {'type': 'string', 'description': 'Target cluster name'}, 'strategy': {'type': 'string', 'description': 'Device plugin strategy', 'enum': ['none', 'time-slicing', 'mig-single', 'mig-mixed'], 'default': 'none'}, 'replicas': {'type': 'integer', 'description': 'Time-slicing replicas per GPU', 'default': 2}}, 'required': ['cluster_name']}),
        Tool(name='k8s_mig_configure', description='Configure Multi-Instance GPU (MIG) partitioning on A100/H100 GPUs. Splits a single GPU into isolated instances for multi-tenant workloads.', inputSchema={'type': 'object', 'properties': {'cluster_name': {'type': 'string', 'description': 'Target cluster name'}, 'mig_profile': {'type': 'string', 'description': 'MIG profile', 'enum': ['1g.5gb', '1g.10gb', '2g.10gb', '3g.20gb', '4g.20gb', '7g.40gb', '7g.80gb']}, 'gpu_indices': {'type': 'array', 'description': 'GPU indices to configure', 'items': {'type': 'integer'}}}, 'required': ['cluster_name', 'mig_profile']}),
        Tool(name='k8s_time_slicing', description='Configure GPU time-slicing for Kubernetes. Allows multiple pods to share a single GPU with configurable oversubscription.', inputSchema={'type': 'object', 'properties': {'cluster_name': {'type': 'string', 'description': 'Target cluster name'}, 'replicas': {'type': 'integer', 'description': 'Virtual GPUs per physical GPU', 'default': 4}, 'oversubscribe': {'type': 'boolean', 'description': 'Allow oversubscription', 'default': True}}, 'required': ['cluster_name']}),
    ]
