"""MCP tool schema definitions."""

from typing import Any, List

try:
    from mcp.types import Tool
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False
    Tool = None

TOOLS = []

if Tool is not None:
    TOOLS = [

        Tool(name='hf_space_deploy', description='Deploy model to HuggingFace Spaces', inputSchema={'type': 'object', 'properties': {'space_name': {'type': 'string', 'description': 'Name of the Space'}, 'model_id': {'type': 'string', 'description': 'HuggingFace model ID'}, 'template': {'type': 'string', 'description': 'Template type', 'enum': ['llm', 'embedding', 'image']}, 'hardware': {'type': 'string', 'description': 'Hardware specification'}, 'sdk': {'type': 'string', 'description': 'SDK to use (e.g., gradio, streamlit)'}}, 'required': ['space_name', 'model_id', 'template']}),
        Tool(name='hf_space_status', description='Get HuggingFace Space deployment status.', inputSchema={'type': 'object', 'properties': {'space_name': {'type': 'string', 'description': 'Space name to check'}}, 'required': ['space_name']}),
        Tool(name='ray_status', description='Get Ray cluster status including node count, resources, memory, and running jobs.', inputSchema={'type': 'object', 'properties': {'detailed': {'type': 'boolean', 'description': 'Include detailed memory and resource info', 'default': True}}, 'required': []}),
        Tool(name='ray_start', description='Start a Ray cluster (head node or worker). For distributed ML training and inference.', inputSchema={'type': 'object', 'properties': {'head': {'type': 'boolean', 'description': 'Start as head node (true) or worker (false)', 'default': True}, 'port': {'type': 'integer', 'description': 'Ray head port', 'default': 6379}, 'num_gpus': {'type': 'integer', 'description': 'Number of GPUs to expose'}, 'head_address': {'type': 'string', 'description': 'Head node address for worker nodes (e.g. 10.0.0.1:6379)'}}, 'required': []}),
        Tool(name='ray_stop', description='Stop the Ray cluster on the current node.', inputSchema={'type': 'object', 'properties': {}, 'required': []}),
        Tool(name='ray_submit_job', description='Submit a job script to the Ray cluster for distributed execution.', inputSchema={'type': 'object', 'properties': {'script': {'type': 'string', 'description': 'Path to the Python script to submit'}, 'job_name': {'type': 'string', 'description': 'Optional job name'}, 'num_gpus': {'type': 'integer', 'description': 'GPU resources to request'}, 'num_cpus': {'type': 'integer', 'description': 'CPU resources to request'}}, 'required': ['script']}),
        Tool(name='ray_list_jobs', description='List all running Ray jobs and tasks.', inputSchema={'type': 'object', 'properties': {}, 'required': []}),
        Tool(name='ray_wide_ep_deploy', description='Generate a Ray Serve LLM Wide-EP (Expert Parallel) deployment for MoE models. Returns Python script and config for distributed MoE serving with EPLB and DeepEP.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID (e.g. zai-org/GLM-5-FP8, deepseek-ai/DeepSeek-V3)'}, 'tp_size': {'type': 'integer', 'description': 'Tensor parallel size per EP rank', 'default': 1}, 'dp_size': {'type': 'integer', 'description': 'Data parallel / EP degree', 'default': 8}, 'gpu_memory_utilization': {'type': 'number', 'description': 'GPU memory fraction', 'default': 0.85}, 'max_model_len': {'type': 'integer', 'description': 'Max sequence length', 'default': 32768}, 'generate_script': {'type': 'boolean', 'description': 'Also generate executable Python script', 'default': True}}, 'required': ['model_id']}),
        Tool(name='ray_disagg_pd_deploy', description='Generate a Ray Serve LLM disaggregated Prefill/Decode deployment. Splits inference into compute-bound prefill and memory-bound decode phases with KV cache transfer via NIXL.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID'}, 'prefill_tp': {'type': 'integer', 'description': 'Prefill tensor parallel size', 'default': 1}, 'prefill_dp': {'type': 'integer', 'description': 'Prefill data parallel size', 'default': 4}, 'decode_tp': {'type': 'integer', 'description': 'Decode tensor parallel size', 'default': 1}, 'decode_dp': {'type': 'integer', 'description': 'Decode data parallel size', 'default': 4}, 'kv_connector': {'type': 'string', 'description': 'KV transfer connector', 'enum': ['NixlConnector', 'LMCacheConnector'], 'default': 'NixlConnector'}, 'generate_script': {'type': 'boolean', 'description': 'Also generate executable Python script', 'default': True}}, 'required': ['model_id']}),
        Tool(name='ray_parallelism_strategy', description='Compute optimal TP/DP/EP parallelism strategy for a given MoE model and GPU count. Returns recommended configuration with rationale.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID (e.g. zai-org/GLM-5-FP8)'}, 'gpu_count': {'type': 'integer', 'description': 'Number of available GPUs', 'default': 8}, 'gpu_memory_gb': {'type': 'number', 'description': 'GPU memory per device in GB', 'default': 80.0}}, 'required': ['model_id']}),
        Tool(name='wandb_list_projects', description='List all Weights & Biases projects for the configured entity.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity (team/username)'}}, 'required': ['api_key']}),
        Tool(name='wandb_list_runs', description='List runs in a W&B project with status, metrics summary, and config.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}, 'project': {'type': 'string', 'description': 'W&B project name'}, 'limit': {'type': 'integer', 'description': 'Max runs to return', 'default': 50}}, 'required': ['api_key', 'project']}),
        Tool(name='wandb_run_details', description='Get detailed info, metrics, and artifacts for a specific W&B run.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'W&B API key'}, 'run_id': {'type': 'string', 'description': 'W&B run ID'}}, 'required': ['api_key', 'run_id']}),
        Tool(name='mlflow_list_experiments', description='List MLflow experiments on the configured tracking server.', inputSchema={'type': 'object', 'properties': {'tracking_uri': {'type': 'string', 'description': 'MLflow tracking server URI'}, 'username': {'type': 'string', 'description': 'Basic auth username'}, 'password': {'type': 'string', 'description': 'Basic auth password'}}, 'required': ['tracking_uri']}),
        Tool(name='mlflow_log_run', description='Log a Terradev training run to MLflow with auto-injected GPU type, provider, cost/hr, and duration as params.', inputSchema={'type': 'object', 'properties': {'tracking_uri': {'type': 'string', 'description': 'MLflow tracking server URI'}, 'experiment_name': {'type': 'string', 'description': 'MLflow experiment name'}, 'run_name': {'type': 'string', 'description': 'Run display name'}, 'gpu_type': {'type': 'string', 'description': 'GPU type used (e.g. H100)'}, 'provider': {'type': 'string', 'description': 'Cloud provider'}, 'cost_per_hour': {'type': 'number', 'description': 'Cost per hour in USD'}, 'duration_seconds': {'type': 'number', 'description': 'Training duration in seconds'}, 'metrics': {'type': 'object', 'description': 'Additional metrics to log'}, 'username': {'type': 'string', 'description': 'Basic auth username'}, 'password': {'type': 'string', 'description': 'Basic auth password'}}, 'required': ['tracking_uri', 'experiment_name', 'run_name']}),
        Tool(name='mlflow_register_model', description='Register a trained model in the MLflow model registry with Terradev provenance tags.', inputSchema={'type': 'object', 'properties': {'tracking_uri': {'type': 'string', 'description': 'MLflow tracking server URI'}, 'model_name': {'type': 'string', 'description': 'Model registry name'}, 'run_id': {'type': 'string', 'description': 'MLflow run ID that produced the model'}, 'model_uri': {'type': 'string', 'description': 'Model artifact URI (e.g. runs:/<run_id>/model)'}, 'tags': {'type': 'object', 'description': 'Additional tags to set on the model version'}, 'username': {'type': 'string', 'description': 'Basic auth username'}, 'password': {'type': 'string', 'description': 'Basic auth password'}}, 'required': ['tracking_uri', 'model_name', 'run_id']}),
        Tool(name='dvc_status', description='Get DVC repository status: tracked files, remotes, and changes since last commit.', inputSchema={'type': 'object', 'properties': {'repo_path': {'type': 'string', 'description': 'Path to the DVC repository'}}, 'required': ['repo_path']}),
        Tool(name='dvc_diff', description='Show DVC diff between two revisions (e.g. training checkpoints). Shows added, modified, deleted files.', inputSchema={'type': 'object', 'properties': {'repo_path': {'type': 'string', 'description': 'Path to the DVC repository'}, 'rev_a': {'type': 'string', 'description': 'Base revision (git ref)'}, 'rev_b': {'type': 'string', 'description': 'Target revision (git ref, default: HEAD)'}}, 'required': ['repo_path']}),
        Tool(name='dvc_stage_checkpoint', description='Atomic checkpoint staging: DVC add + push + git commit in one operation. Promotes a training checkpoint to versioned storage.', inputSchema={'type': 'object', 'properties': {'repo_path': {'type': 'string', 'description': 'Path to the DVC repository'}, 'checkpoint_path': {'type': 'string', 'description': 'Path to the checkpoint file/directory to stage'}, 'message': {'type': 'string', 'description': 'Git commit message', 'default': 'Stage checkpoint via Terradev'}, 'remote': {'type': 'string', 'description': 'DVC remote name to push to'}}, 'required': ['repo_path', 'checkpoint_path']}),
        Tool(name='dvc_push', description='Push DVC-tracked data to the configured remote storage.', inputSchema={'type': 'object', 'properties': {'repo_path': {'type': 'string', 'description': 'Path to the DVC repository'}, 'remote': {'type': 'string', 'description': 'DVC remote name (optional, uses default)'}}, 'required': ['repo_path']}),
        Tool(name='hf_list_models', description='Search and browse HuggingFace Hub models. Filter by author, task, library. Returns model ID, downloads, likes, and tags.', inputSchema={'type': 'object', 'properties': {'author': {'type': 'string', 'description': 'Filter by author/org (e.g. meta-llama, mistralai)'}, 'search': {'type': 'string', 'description': "Search query (e.g. 'code generation', 'llama')"}, 'limit': {'type': 'integer', 'description': 'Max results', 'default': 20}, 'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['api_key']}),
        Tool(name='hf_list_datasets', description='Search and browse HuggingFace Hub datasets. Filter by author and search query.', inputSchema={'type': 'object', 'properties': {'author': {'type': 'string', 'description': 'Filter by author/org'}, 'search': {'type': 'string', 'description': 'Search query'}, 'limit': {'type': 'integer', 'description': 'Max results', 'default': 20}, 'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['api_key']}),
        Tool(name='hf_model_info', description='Get detailed model info: architecture, size, downloads, license, tags, pipeline_tag, and model card.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID (e.g. meta-llama/Llama-3.3-70B-Instruct)'}, 'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['model_id', 'api_key']}),
        Tool(name='hf_create_endpoint', description='Create a HuggingFace Inference Endpoint (paid GPU endpoint). Supports custom GPU types, regions, and scaling.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID'}, 'endpoint_name': {'type': 'string', 'description': 'Endpoint name'}, 'instance_type': {'type': 'string', 'description': 'Instance type (e.g. nvidia-a100, nvidia-l4)'}, 'instance_size': {'type': 'string', 'description': 'Instance size (e.g. x1, x2, x4)'}, 'region': {'type': 'string', 'description': 'Region (e.g. us-east-1, eu-west-1)', 'default': 'us-east-1'}, 'min_replicas': {'type': 'integer', 'description': 'Min replicas (0 for scale-to-zero)', 'default': 0}, 'max_replicas': {'type': 'integer', 'description': 'Max replicas', 'default': 1}, 'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['model_id', 'endpoint_name', 'instance_type', 'api_key']}),
        Tool(name='hf_list_endpoints', description='List all active HuggingFace Inference Endpoints with status, URL, and cost.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['api_key']}),
        Tool(name='hf_endpoint_info', description='Get detailed info about a specific HuggingFace Inference Endpoint: status, URL, scaling config, cost.', inputSchema={'type': 'object', 'properties': {'endpoint_name': {'type': 'string', 'description': 'Endpoint name'}, 'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['endpoint_name', 'api_key']}),
        Tool(name='hf_delete_endpoint', description='Delete a HuggingFace Inference Endpoint.', inputSchema={'type': 'object', 'properties': {'endpoint_name': {'type': 'string', 'description': 'Endpoint name to delete'}, 'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['endpoint_name', 'api_key']}),
        Tool(name='hf_endpoint_infer', description='Run inference on a HuggingFace Inference Endpoint. Supports text generation, embeddings, and custom inputs.', inputSchema={'type': 'object', 'properties': {'endpoint_name': {'type': 'string', 'description': 'Endpoint name'}, 'inputs': {'type': 'string', 'description': 'Input text or prompt'}, 'parameters': {'type': 'object', 'description': 'Generation parameters (max_new_tokens, temperature, etc.)'}, 'api_key': {'type': 'string', 'description': 'HuggingFace API token'}}, 'required': ['endpoint_name', 'inputs', 'api_key']}),
        Tool(name='hf_smart_template', description='Auto-generate an optimized deployment template for any HuggingFace model. Analyzes model size, architecture, and quantization to select optimal hardware and generate ready-to-deploy configs.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID (e.g. meta-llama/Llama-3.3-70B-Instruct)'}, 'template_type': {'type': 'string', 'description': 'Template type', 'enum': ['auto', 'chat', 'embedding', 'vision', 'audio'], 'default': 'auto'}, 'space_name': {'type': 'string', 'description': 'Optional HF Space name for deployment'}}, 'required': ['model_id']}),
        Tool(name='hf_hardware_recommend', description='Get hardware recommendation with cost breakdown for any HuggingFace model. Returns optimal GPU type, estimated cost, and performance score.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID'}, 'budget_constraint': {'type': 'number', 'description': 'Max $/hr budget (optional)'}}, 'required': ['model_id']}),
        Tool(name='hf_hardware_compare', description='Compare all hardware options for a HuggingFace model. Returns side-by-side cost, performance, and compatibility analysis.', inputSchema={'type': 'object', 'properties': {'model_id': {'type': 'string', 'description': 'HuggingFace model ID'}}, 'required': ['model_id']}),
        Tool(name='langchain_create_workflow', description='Create a LangChain workflow.', inputSchema={'type': 'object', 'properties': {'workflow_config': {'type': 'object', 'description': 'Workflow configuration (name, steps, model, tools)'}, 'api_key': {'type': 'string', 'description': 'LangChain API key'}}, 'required': ['workflow_config', 'api_key']}),
        Tool(name='langchain_create_sglang_pipeline', description='Create an SGLang model-serving pipeline via LangChain. Connects LangChain agents to SGLang inference endpoints.', inputSchema={'type': 'object', 'properties': {'pipeline_config': {'type': 'object', 'description': 'Pipeline config (model, endpoint, temperature, max_tokens)'}, 'api_key': {'type': 'string', 'description': 'LangChain API key'}}, 'required': ['pipeline_config', 'api_key']}),
        Tool(name='langgraph_create_workflow', description='Create a LangGraph stateful workflow with monitoring. Supports agent graphs, tool calling, and state persistence.', inputSchema={'type': 'object', 'properties': {'graph_config': {'type': 'object', 'description': 'Graph configuration (nodes, edges, state_schema)'}, 'api_key': {'type': 'string', 'description': 'LangChain API key'}}, 'required': ['graph_config', 'api_key']}),
        Tool(name='langgraph_orchestrator_worker', description='Create an orchestrator-worker pattern workflow in LangGraph. The orchestrator delegates tasks to specialized worker agents.', inputSchema={'type': 'object', 'properties': {'workflow_config': {'type': 'object', 'description': 'Orchestrator-worker config (orchestrator_prompt, workers, routing_strategy)'}, 'api_key': {'type': 'string', 'description': 'LangChain API key'}}, 'required': ['workflow_config', 'api_key']}),
        Tool(name='langgraph_evaluation_workflow', description='Create an evaluator-optimizer workflow in LangGraph. Generates outputs, evaluates quality, and iteratively improves.', inputSchema={'type': 'object', 'properties': {'evaluation_config': {'type': 'object', 'description': 'Evaluation config (generator_prompt, evaluator_criteria, max_iterations)'}, 'api_key': {'type': 'string', 'description': 'LangChain API key'}}, 'required': ['evaluation_config', 'api_key']}),
        Tool(name='langgraph_workflow_status', description='Get the status and metrics of a LangGraph workflow execution.', inputSchema={'type': 'object', 'properties': {'workflow_id': {'type': 'string', 'description': 'Workflow ID to check'}, 'api_key': {'type': 'string', 'description': 'LangChain API key'}}, 'required': ['workflow_id', 'api_key']}),
        Tool(name='wandb_create_dashboard', description='Create a custom W&B dashboard with GPU metrics, training loss, and cost panels.', inputSchema={'type': 'object', 'properties': {'dashboard_config': {'type': 'object', 'description': 'Dashboard config (name, panels, metrics)'}, 'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}}, 'required': ['dashboard_config', 'api_key']}),
        Tool(name='wandb_create_terradev_dashboard', description='Auto-create a Terradev-specific W&B dashboard with GPU utilization, cost tracking, training metrics, and infrastructure panels.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}, 'project': {'type': 'string', 'description': 'W&B project name'}}, 'required': ['api_key']}),
        Tool(name='wandb_create_report', description='Create a W&B report with custom sections, charts, and narrative text.', inputSchema={'type': 'object', 'properties': {'report_config': {'type': 'object', 'description': 'Report config (title, sections, metrics, description)'}, 'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}}, 'required': ['report_config', 'api_key']}),
        Tool(name='wandb_create_terradev_report', description='Auto-generate a Terradev infrastructure report: GPU costs, provider comparison, training efficiency, and recommendations.', inputSchema={'type': 'object', 'properties': {'metrics_data': {'type': 'object', 'description': 'Metrics data to include (gpu_costs, training_runs, provider_stats)'}, 'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}}, 'required': ['api_key']}),
        Tool(name='wandb_setup_alerts', description='Set up custom W&B alerts for GPU metrics: cost thresholds, utilization drops, training anomalies.', inputSchema={'type': 'object', 'properties': {'alert_config': {'type': 'object', 'description': 'Alert config (metric, threshold, condition, notification_channel)'}, 'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}}, 'required': ['alert_config', 'api_key']}),
        Tool(name='wandb_create_terradev_alerts', description='Auto-create standard Terradev alerts: GPU cost > budget, utilization < 50%, training loss spike, straggler detection.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}}, 'required': ['api_key']}),
        Tool(name='wandb_dashboard_status', description='Get comprehensive W&B monitoring overview: dashboards, reports, alerts, active runs.', inputSchema={'type': 'object', 'properties': {'api_key': {'type': 'string', 'description': 'W&B API key'}, 'entity': {'type': 'string', 'description': 'W&B entity'}}, 'required': ['api_key']}),
        Tool(name='phoenix_test', description='Test connection to Arize Phoenix server. Returns collector endpoint and project count.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='phoenix_projects', description='List Phoenix projects (trace namespaces).', inputSchema={'type': 'object', 'properties': {'limit': {'type': 'integer', 'description': 'Max projects to return', 'default': 50}}}),
        Tool(name='phoenix_spans', description='List recent spans for a Phoenix project. Supports SpanQuery DSL filters like "span_kind == \'RETRIEVER\'" or "status_code == \'ERROR\'".', inputSchema={'type': 'object', 'properties': {'project': {'type': 'string', 'description': 'Project ID or name'}, 'filter': {'type': 'string', 'description': 'SpanQuery DSL filter expression'}, 'limit': {'type': 'integer', 'description': 'Max spans to return', 'default': 20}}}),
        Tool(name='phoenix_trace', description='View full execution tree for a specific trace ID. Shows span hierarchy, latencies, and token counts.', inputSchema={'type': 'object', 'properties': {'trace_id': {'type': 'string', 'description': 'Trace ID to inspect'}, 'project': {'type': 'string', 'description': 'Project ID or name'}}, 'required': ['trace_id']}),
        Tool(name='phoenix_otel_env', description='Generate OpenTelemetry environment variables for instrumenting serving pods with Phoenix tracing.', inputSchema={'type': 'object', 'properties': {'project': {'type': 'string', 'description': 'Project name'}}}),
        Tool(name='phoenix_snippet', description='Generate Python instrumentation snippet for adding Phoenix tracing to LLM applications.', inputSchema={'type': 'object', 'properties': {'project': {'type': 'string', 'description': 'Project name'}}}),
        Tool(name='phoenix_k8s', description='Generate Kubernetes deployment manifest for self-hosted Arize Phoenix server.', inputSchema={'type': 'object', 'properties': {'namespace': {'type': 'string', 'description': 'K8s namespace', 'default': 'observability'}}}),
        Tool(name='guardrails_test', description='Test connection to NeMo Guardrails server.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='guardrails_chat', description='Send a message through NeMo Guardrails and return the safety-filtered response. Applies topical, jailbreak, PII, and factcheck rails.', inputSchema={'type': 'object', 'properties': {'message': {'type': 'string', 'description': 'Message to send through guardrails'}, 'config_id': {'type': 'string', 'description': 'Guardrails config_id to use'}}, 'required': ['message']}),
        Tool(name='guardrails_generate_config', description='Generate default Colang 2.x guardrails configuration files (topical, jailbreak, PII, factcheck rails).', inputSchema={'type': 'object', 'properties': {'config_id': {'type': 'string', 'description': 'Config ID name'}, 'output_dir': {'type': 'string', 'description': 'Output directory', 'default': './guardrails'}}}),
        Tool(name='guardrails_k8s', description='Generate Kubernetes deployment manifest for NeMo Guardrails server (standalone or sidecar mode).', inputSchema={'type': 'object', 'properties': {'namespace': {'type': 'string', 'description': 'K8s namespace', 'default': 'guardrails'}}}),
        Tool(name='qdrant_test', description='Test connection to Qdrant vector database. Returns cluster info and collection count.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='qdrant_collections', description='List all Qdrant vector collections with their point counts and configurations.', inputSchema={'type': 'object', 'properties': {}}),
        Tool(name='qdrant_create_collection', description='Create a Qdrant vector collection. Auto-configures vector dimensions from embedding model name.', inputSchema={'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Collection name'}, 'embedding_model': {'type': 'string', 'description': 'Embedding model (auto-sets vector size, e.g. BAAI/bge-large-en-v1.5)'}}}),
        Tool(name='qdrant_info', description='Get detailed info and stats for a Qdrant collection.', inputSchema={'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Collection name'}}}),
        Tool(name='qdrant_count', description='Count points (vectors) in a Qdrant collection.', inputSchema={'type': 'object', 'properties': {'name': {'type': 'string', 'description': 'Collection name'}}}),
        Tool(name='qdrant_k8s', description='Generate Kubernetes StatefulSet manifest for self-hosted Qdrant vector database.', inputSchema={'type': 'object', 'properties': {'namespace': {'type': 'string', 'description': 'K8s namespace', 'default': 'vector-db'}}}),
        Tool(name='deepeval_run', description='Run a DeepEval test suite from a Python test file.', inputSchema={'type': 'object', 'properties': {'file': {'type': 'string', 'description': 'DeepEval test file path', 'default': 'test_deepeval.py'}}, 'required': []}),
        Tool(name='deepeval_metrics', description='List available DeepEval metrics for LLM evaluation.', inputSchema={'type': 'object', 'properties': {}, 'required': []}),
        Tool(name='deepeval_evaluate', description='Evaluate a single LLM output with a DeepEval metric (AnswerRelevancy, Faithfulness, Hallucination, etc.).', inputSchema={'type': 'object', 'properties': {'input': {'type': 'string', 'description': 'Test input/prompt'}, 'actual_output': {'type': 'string', 'description': 'Actual LLM output'}, 'metric': {'type': 'string', 'description': 'DeepEval metric name', 'enum': ['AnswerRelevancyMetric', 'FaithfulnessMetric', 'ContextualRelevancyMetric', 'ContextualPrecisionMetric', 'ContextualRecallMetric', 'HallucinationMetric', 'BiasMetric', 'ToxicityMetric', 'SummarizationMetric', 'RagasMetric']}, 'expected_output': {'type': 'string', 'description': 'Expected output (optional)'}, 'context': {'type': 'string', 'description': 'Ground-truth context, comma-separated (optional)'}, 'retrieval_context': {'type': 'string', 'description': 'Retrieval context, comma-separated (optional)'}, 'threshold': {'type': 'number', 'description': 'Passing threshold', 'default': 0.5}}, 'required': ['input', 'actual_output', 'metric']}),
        Tool(name='deepeval_init', description='Generate a starter DeepEval test file.', inputSchema={'type': 'object', 'properties': {'output': {'type': 'string', 'description': 'Output test file path', 'default': 'test_deepeval.py'}}, 'required': []}),
    ]
