"""MCP tool schema definitions."""

from typing import Any, List

try:
    from mcp.types import Tool
    MCP_AVAILABLE = True
except ImportError:
    MCP_AVAILABLE = False
    Tool = None

TOOLS = []

if Tool is not None:
    TOOLS = [
        Tool(name='database_weaviate_create_collection', description='Create a Weaviate collection.', inputSchema={'type': 'object', 'properties': {'name': {'description': 'Collection name', 'type': 'string'}, 'vector_size': {'description': 'Vector dimension (omit when using vectorizer)', 'type': 'integer'}, 'vectorizer': {'description': 'Built-in vectorizer module', 'type': 'string', 'enum': ['openai', 'cohere', 'huggingface', 'ollama']}, 'properties': {'description': 'JSON list of properties [{name, data_type}]', 'type': 'string', 'default': '[]'}, 'environment': {'description': 'environment', 'type': 'string', 'enum': ['local', 'embedded', 'cloud', 'custom'], 'default': 'local'}, 'host': {'description': 'host', 'type': 'string', 'default': 'localhost'}, 'http_port': {'description': 'http_port', 'type': 'integer', 'default': 8080}, 'grpc_port': {'description': 'grpc_port', 'type': 'integer', 'default': 50051}, 'secure': {'description': 'secure', 'type': 'boolean', 'default': False}, 'cluster_url': {'description': 'cluster_url', 'type': 'string'}, 'api_key': {'description': 'api_key', 'type': 'string'}, 'headers': {'description': 'headers', 'type': 'string', 'default': '{}'}}, 'required': ['name']}),
        Tool(name='database_weaviate_delete_collection', description='Delete a Weaviate collection.', inputSchema={'type': 'object', 'properties': {'name': {'description': 'Collection name', 'type': 'string'}, 'environment': {'description': 'environment', 'type': 'string', 'enum': ['local', 'embedded', 'cloud', 'custom'], 'default': 'local'}, 'host': {'description': 'host', 'type': 'string', 'default': 'localhost'}, 'http_port': {'description': 'http_port', 'type': 'integer', 'default': 8080}, 'grpc_port': {'description': 'grpc_port', 'type': 'integer', 'default': 50051}, 'secure': {'description': 'secure', 'type': 'boolean', 'default': False}, 'cluster_url': {'description': 'cluster_url', 'type': 'string'}, 'api_key': {'description': 'api_key', 'type': 'string'}, 'headers': {'description': 'headers', 'type': 'string', 'default': '{}'}}, 'required': ['name']}),
        Tool(name='database_weaviate_hybrid_search', description='Hybrid vector + BM25 search in a Weaviate collection.', inputSchema={'type': 'object', 'properties': {'collection': {'description': 'collection', 'type': 'string'}, 'query': {'description': 'Text query', 'type': 'string'}, 'alpha': {'description': 'Balance between vector (1.0) and keyword (0.0)', 'type': 'number', 'default': 0.7}, 'top_k': {'description': 'top_k', 'type': 'integer', 'default': 10}, 'environment': {'description': 'environment', 'type': 'string', 'enum': ['local', 'embedded', 'cloud', 'custom'], 'default': 'local'}, 'host': {'description': 'host', 'type': 'string', 'default': 'localhost'}, 'http_port': {'description': 'http_port', 'type': 'integer', 'default': 8080}, 'grpc_port': {'description': 'grpc_port', 'type': 'integer', 'default': 50051}, 'secure': {'description': 'secure', 'type': 'boolean', 'default': False}, 'cluster_url': {'description': 'cluster_url', 'type': 'string'}, 'api_key': {'description': 'api_key', 'type': 'string'}, 'headers': {'description': 'headers', 'type': 'string', 'default': '{}'}}, 'required': ['collection', 'query']}),
        Tool(name='database_weaviate_insert', description='Insert objects into a Weaviate collection.', inputSchema={'type': 'object', 'properties': {'collection': {'description': 'collection', 'type': 'string'}, 'objects': {'description': 'JSON list of objects [{properties: {...}, vector: [...]}]', 'type': 'string'}, 'environment': {'description': 'environment', 'type': 'string', 'enum': ['local', 'embedded', 'cloud', 'custom'], 'default': 'local'}, 'host': {'description': 'host', 'type': 'string', 'default': 'localhost'}, 'http_port': {'description': 'http_port', 'type': 'integer', 'default': 8080}, 'grpc_port': {'description': 'grpc_port', 'type': 'integer', 'default': 50051}, 'secure': {'description': 'secure', 'type': 'boolean', 'default': False}, 'cluster_url': {'description': 'cluster_url', 'type': 'string'}, 'api_key': {'description': 'api_key', 'type': 'string'}, 'headers': {'description': 'headers', 'type': 'string', 'default': '{}'}}, 'required': ['collection', 'objects']}),
        Tool(name='database_weaviate_list_collections', description='List Weaviate collections.', inputSchema={'type': 'object', 'properties': {'environment': {'description': 'environment', 'type': 'string', 'enum': ['local', 'embedded', 'cloud', 'custom'], 'default': 'local'}, 'host': {'description': 'host', 'type': 'string', 'default': 'localhost'}, 'http_port': {'description': 'http_port', 'type': 'integer', 'default': 8080}, 'grpc_port': {'description': 'grpc_port', 'type': 'integer', 'default': 50051}, 'secure': {'description': 'secure', 'type': 'boolean', 'default': False}, 'cluster_url': {'description': 'cluster_url', 'type': 'string'}, 'api_key': {'description': 'api_key', 'type': 'string'}, 'headers': {'description': 'headers', 'type': 'string', 'default': '{}'}}}),
        Tool(name='database_weaviate_query', description='Vector similarity search in a Weaviate collection.', inputSchema={'type': 'object', 'properties': {'collection': {'description': 'collection', 'type': 'string'}, 'vector': {'description': 'JSON array of floats', 'type': 'string'}, 'top_k': {'description': 'top_k', 'type': 'integer', 'default': 10}, 'filters': {'description': 'JSON filter payload', 'type': 'string', 'default': '{}'}, 'environment': {'description': 'environment', 'type': 'string', 'enum': ['local', 'embedded', 'cloud', 'custom'], 'default': 'local'}, 'host': {'description': 'host', 'type': 'string', 'default': 'localhost'}, 'http_port': {'description': 'http_port', 'type': 'integer', 'default': 8080}, 'grpc_port': {'description': 'grpc_port', 'type': 'integer', 'default': 50051}, 'secure': {'description': 'secure', 'type': 'boolean', 'default': False}, 'cluster_url': {'description': 'cluster_url', 'type': 'string'}, 'api_key': {'description': 'api_key', 'type': 'string'}, 'headers': {'description': 'headers', 'type': 'string', 'default': '{}'}}, 'required': ['collection', 'vector']}),
        Tool(name='database_weaviate_up', description='Initialize a Weaviate connection.', inputSchema={'type': 'object', 'properties': {'environment': {'description': 'environment', 'type': 'string', 'enum': ['local', 'embedded', 'cloud', 'custom'], 'default': 'local'}, 'host': {'description': 'Weaviate HTTP host', 'type': 'string', 'default': 'localhost'}, 'http_port': {'description': 'Weaviate HTTP port', 'type': 'integer', 'default': 8080}, 'grpc_port': {'description': 'Weaviate gRPC port', 'type': 'integer', 'default': 50051}, 'secure': {'description': 'Use HTTPS/gRPC TLS', 'type': 'boolean', 'default': False}, 'cluster_url': {'description': 'Weaviate Cloud cluster URL', 'type': 'string'}, 'api_key': {'description': 'Weaviate API key (or WEAVIATE_API_KEY env)', 'type': 'string'}, 'headers': {'description': 'JSON headers for the client', 'type': 'string', 'default': '{}'}}}),
    ]
