apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lorax.fullname" . }}
  labels:
    app: {{ include "lorax.name" . }}
    chart: {{ include "lorax.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
