backoffLimit: 3
budget:
  enforce: false
  maxHourlyRate: null
gpu:
  count: 1
  memory: 16
  nodeLabel: NVIDIA-A100-SXM4-80GB
  storage: 100
  type: A100
image:
  pullPolicy: IfNotPresent
  repository: test
  tag: latest
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 15s
    path: /metrics
nodeSelector:
  nvidia.com/gpu.product: '{{ .Values.gpu.nodeLabel }}'
podSecurityContext:
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
resources:
  limits:
    cpu: '12'
    memory: 176Gi
    nvidia.com/gpu: '1'
  requests:
    cpu: '6'
    memory: 88Gi
    nvidia.com/gpu: '1'
restartPolicy: Never
securityContext:
  capabilities:
    drop:
    - ALL
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
serviceAccount:
  annotations: {}
  create: true
  name: ''
terradev:
  provider: auto
  region: us-east-1
  spot: false
tolerations:
- effect: NoSchedule
  key: nvidia.com/gpu
  operator: Exists
ttlSecondsAfterFinished: 300
workloadType: Job
