apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "terradev.fullname" . }}-storage
  labels:
    {{- include "terradev.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.gpu.storage }}Gi
  {{- if .Values.persistence }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- else }}
  storageClassName: gp3
  {{- end }}