#!/bin/bash
# Terradev Account Setup Automation Script
# Sets up all necessary accounts and API keys

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
ENV_FILE=".env"
SETUP_LOG="setup.log"

# Initialize log
echo "Terradev Account Setup Log - $(date)" > $SETUP_LOG

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1" | tee -a $SETUP_LOG
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a $SETUP_LOG
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a $SETUP_LOG
}

print_header() {
    echo -e "${BLUE}$1${NC}" | tee -a $SETUP_LOG
}

# Function to prompt for API key
prompt_api_key() {
    local key_name=$1
    local description=$2
    local required=$3
    
    print_header "🔧 Setting up $description"
    
    if [ "$required" = "true" ]; then
        while true; do
            echo -n "Enter your $key_name: "
            read -s api_key
            echo
            if [ -n "$api_key" ]; then
                echo "$key_name=$api_key" >> $ENV_FILE
                print_status "$key_name configured"
                break
            else
                print_error "$key_name is required"
            fi
        done
    else
        echo -n "Enter your $key_name (optional, press Enter to skip): "
        read -s api_key
        echo
        if [ -n "$api_key" ]; then
            echo "$key_name=$api_key" >> $ENV_FILE
            print_status "$key_name configured"
        else
            print_warning "$key_name skipped"
        fi
    fi
}

# Function to prompt for file path
prompt_file_path() {
    local key_name=$1
    local description=$2
    local default_path=$3
    
    print_header "🔧 Setting up $description"
    
    echo -n "Enter path to $key_name (default: $default_path): "
    read file_path
    
    if [ -z "$file_path" ]; then
        file_path="$default_path"
    fi
    
    echo "$key_name=$file_path" >> $ENV_FILE
    print_status "$key_name set to: $file_path"
}

# Function to open browser for signup
open_signup_page() {
    local url=$1
    local service_name=$2
    
    print_header "🌐 Opening signup page for $service_name"
    
    if command -v open > /dev/null; then
        open "$url"
    elif command -v xdg-open > /dev/null; then
        xdg-open "$url"
    else
        print_warning "Please manually open: $url"
    fi
    
    echo "Please complete the signup and return here to enter your API key."
    echo "Press Enter when you have your API key..."
    read
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to validate API key format
validate_api_key() {
    local key=$1
    local min_length=$2
    
    if [ ${#key} -lt $min_length ]; then
        print_error "API key seems too short (minimum $min_length characters)"
        return 1
    fi
    
    return 0
}

# Main setup function
main() {
    print_header "🚀 Terradev Account Setup Automation"
    print_status "This script will help you set up all necessary accounts and API keys"
    print_status "Setup time: ~15-30 minutes"
    print_status "Total cost: $0 (all free tiers)"
    echo
    
    # Create .env file
    if [ -f "$ENV_FILE" ]; then
        print_warning ".env file already exists. Backing up to .env.backup"
        cp "$ENV_FILE" "$ENV_FILE.backup"
    fi
    
    # Initialize .env file
    cat > $ENV_FILE << 'EOF'
# Terradev Environment Configuration
# Generated by setup script on $(date)

# Geolocation APIs
EOF
    
    print_status "Created .env file"
    
    # Phase 1: Essential APIs (no signup required)
    print_header "📍 Phase 1: Essential Geolocation APIs"
    print_status "IPapi.co - No setup required (unlimited free)"
    print_status "ip-api.com - No setup required (unlimited free)"
    echo "" >> $ENV_FILE
    echo "# IPapi.co - Direct access (no API key needed)" >> $ENV_FILE
    echo "# ip-api.com - Direct access (no API key needed)" >> $ENV_FILE
    echo "" >> $ENV_FILE
    
    # Phase 2: Core Service APIs
    print_header "🔧 Phase 2: Core Service APIs"
    
    # RunPod
    open_signup_page "https://runpod.io/signup" "RunPod"
    prompt_api_key "RUNPOD_API_KEY" "RunPod API Key" "true"
    
    # Cloudflare
    open_signup_page "https://dash.cloudflare.com/sign-up" "Cloudflare"
    prompt_api_key "CLOUDFLARE_API_KEY" "Cloudflare API Key" "true"
    echo -n "Enter your Cloudflare email: "
    read cloudflare_email
    echo "CLOUDFLARE_EMAIL=$cloudflare_email" >> $ENV_FILE
    
    # GitHub
    open_signup_page "https://github.com/signup" "GitHub"
    echo "After signing up, go to Settings > Developer settings > Personal access tokens"
    open_signup_page "https://github.com/settings/tokens/new" "GitHub Token"
    prompt_api_key "GITHUB_TOKEN" "GitHub Personal Access Token" "true"
    
    # Phase 3: Cloud Provider APIs
    print_header "☁️ Phase 3: Cloud Provider APIs"
    print_warning "This phase requires more detailed setup. Please follow the instructions carefully."
    
    # AWS
    print_header "🔧 Setting up AWS"
    open_signup_page "https://aws.amazon.com/free" "AWS Free Tier"
    echo "After creating your AWS account:"
    echo "1. Go to IAM > Users > Create user"
    echo "2. Select 'Access key - Programmatic access'"
    echo "3. Attach policies: CloudWatchReadOnlyAccess, AmazonSageMakerReadOnly"
    echo "4. Copy the Access Key ID and Secret Access Key"
    
    prompt_api_key "AWS_ACCESS_KEY_ID" "AWS Access Key ID" "true"
    prompt_api_key "AWS_SECRET_ACCESS_KEY" "AWS Secret Access Key" "true"
    echo -n "Enter your AWS region (default: us-east-1): "
    read aws_region
    echo "AWS_REGION=${aws_region:-us-east-1}" >> $ENV_FILE
    
    # GCP
    print_header "🔧 Setting up Google Cloud Platform"
    open_signup_page "https://cloud.google.com/free" "GCP Free Tier"
    echo "After creating your GCP project:"
    echo "1. Go to IAM & Admin > Service Accounts"
    echo "2. Create service account"
    echo "3. Grant roles: Monitoring Viewer, Cloud Trace Agent"
    echo "4. Create and download JSON key"
    
    prompt_file_path "GOOGLE_APPLICATION_CREDENTIALS" "GCP Service Account JSON" "/path/to/gcp-service-account.json"
    
    # Azure
    print_header "🔧 Setting up Microsoft Azure"
    open_signup_page "https://azure.microsoft.com/free" "Azure Free Tier"
    echo "After creating your Azure account:"
    echo "1. Go to Azure Active Directory > App registrations"
    echo "2. Create new app registration"
    echo "3. Go to Certificates & secrets > New client secret"
    echo "4. Copy Application ID, Client Secret, and Tenant ID"
    
    prompt_api_key "AZURE_CLIENT_ID" "Azure Application ID" "true"
    prompt_api_key "AZURE_CLIENT_SECRET" "Azure Client Secret" "true"
    prompt_api_key "AZURE_TENANT_ID" "Azure Tenant ID" "true"
    
    # Phase 4: Additional GPU Providers
    print_header "🚀 Phase 4: Additional GPU Providers"
    
    # Lambda Labs
    open_signup_page "https://lambdalabs.com/signup" "Lambda Labs"
    prompt_api_key "LAMBDA_API_KEY" "Lambda Labs API Key" "false"
    
    # CoreWeave
    open_signup_page "https://coreweave.com/signup" "CoreWeave"
    prompt_api_key "COREWEAVE_API_KEY" "CoreWeave API Key" "false"
    
    # Phase 5: DevOps & Monitoring
    print_header "📊 Phase 5: DevOps & Monitoring"
    
    # Grafana
    open_signup_page "https://grafana.com/signup" "Grafana Cloud"
    prompt_api_key "GRAFANA_API_KEY" "Grafana API Key" "false"
    echo -n "Enter your Grafana URL (default: https://grafana.com): "
    read grafana_url
    echo "GRAFANA_URL=${grafana_url:-https://grafana.com}" >> $ENV_FILE
    
    # Slack (optional)
    print_header "💬 Phase 6: Communication (Optional)"
    echo "Slack integration is optional but recommended for notifications"
    read -p "Do you want to setup Slack integration? (y/n): " setup_slack
    
    if [ "$setup_slack" = "y" ]; then
        open_signup_page "https://slack.com/create" "Slack Workspace"
        echo "After creating your workspace:"
        echo "1. Go to api.slack.com/apps > Create New App"
        echo "2. Add Bot Token Scopes: chat:write, channels:read"
        echo "3. Install app to workspace"
        echo "4. Copy Bot User OAuth Token"
        
        prompt_api_key "SLACK_BOT_TOKEN" "Slack Bot Token" "false"
        prompt_api_key "SLACK_APP_TOKEN" "Slack App Token" "false"
    fi
    
    # Phase 7: Performance Testing
    print_header "⚡ Phase 7: Performance Testing (Optional)"
    read -p "Do you want to setup performance testing APIs? (y/n): " setup_perf
    
    if [ "$setup_perf" = "y" ]; then
        open_signup_page "https://www.webpagetest.org/signup" "WebPageTest"
        prompt_api_key "WEBPAGETEST_API_KEY" "WebPageTest API Key" "false"
        
        open_signup_page "https://gtmetrix.com/signup" "GTmetrix"
        prompt_api_key "GTMETRIX_API_KEY" "GTmetrix API Key" "false"
    fi
    
    # Optional: IPinfo.io and MaxMind
    print_header "🌍 Phase 8: Enhanced Geolocation (Optional)"
    read -p "Do you want to setup enhanced geolocation APIs? (y/n): " setup_geo
    
    if [ "$setup_geo" = "y" ]; then
        open_signup_page "https://ipinfo.io/signup" "IPinfo.io"
        prompt_api_key "IPINFO_API_KEY" "IPinfo.io API Key" "false"
        
        open_signup_page "https://www.maxmind.com/en/geolite2/signup" "MaxMind"
        prompt_api_key "MAXMIND_ACCOUNT_ID" "MaxMind Account ID" "false"
        prompt_api_key "MAXMIND_LICENSE_KEY" "MaxMind License Key" "false"
    fi
    
    # Final setup
    print_header "✅ Setup Complete!"
    
    # Add final comments to .env file
    cat >> $ENV_FILE << 'EOF'

# Optional: Kubernetes configuration
# KUBECONFIG=/path/to/kubeconfig

# Optional: Databricks configuration
# DATABRICKS_API_TOKEN=your_databricks_token
# DATABRICKS_HOST=https://your-databricks-instance.com

# Optional: Fastly API key
# FASTLY_API_KEY=your_fastly_api_key

# Optional: Jenkins configuration
# JENKINS_API_TOKEN=your_jenkins_token
# JENKINS_URL=https://your-jenkins-instance.com
EOF
    
    print_status "✅ All configurations saved to $ENV_FILE"
    print_status "✅ Setup log saved to $SETUP_LOG"
    print_status "✅ Total accounts configured: $(grep -c "=" $ENV_FILE)"
    
    echo
    print_header "🎯 Next Steps"
    echo "1. Review your .env file"
    echo "2. Test API connections with: python test_apis.py"
    echo "3. Run the latency arbitrage engine: python latency_arbitrage_engine.py"
    echo "4. Check the setup log: $SETUP_LOG"
    
    echo
    print_header "🔧 Quick Test Commands"
    echo "# Test geolocation"
    echo "curl 'https://ipapi.co/json/'"
    echo
    echo "# Test RunPod API"
    echo "curl -H \"Authorization: Bearer \$RUNPOD_API_KEY\" 'https://api.runpod.io/v1/gpu'"
    echo
    echo "# Test Cloudflare API"
    echo "curl -H \"Authorization: Bearer \$CLOUDFLARE_API_KEY\" 'https://api.cloudflare.com/client/v4/ips'"
    
    echo
    print_header "🚀 Ready to launch Terradev!"
    print_status "Your latency arbitrage system is now ready to use!"
}

# Check dependencies
check_dependencies() {
    print_header "🔍 Checking dependencies"
    
    local missing_deps=()
    
    if ! command_exists curl; then
        missing_deps+=("curl")
    fi
    
    if ! command_exists python3; then
        missing_deps+=("python3")
    fi
    
    if [ ${#missing_deps[@]} -gt 0 ]; then
        print_error "Missing dependencies: ${missing_deps[*]}"
        print_status "Please install missing dependencies and run again"
        exit 1
    fi
    
    print_status "✅ All dependencies satisfied"
}

# Run setup
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Terradev Account Setup Script"
    echo ""
    echo "Usage: $0 [options]"
    echo ""
    echo "Options:"
    echo "  --help, -h     Show this help message"
    echo "  --quick        Quick setup (essential APIs only)"
    echo "  --full         Full setup (all APIs)"
    echo ""
    echo "Examples:"
    echo "  $0             # Interactive setup"
    echo "  $0 --quick     # Quick setup with essential APIs only"
    echo "  $0 --full      # Full setup with all optional APIs"
    exit 0
fi

if [ "$1" = "--quick" ]; then
    print_header "🚀 Quick Setup Mode"
    print_status "Setting up essential APIs only"
    
    # Quick setup - only essential APIs
    cat > $ENV_FILE << 'EOF'
# Terradev Quick Setup - Essential APIs Only
# Generated on $(date)

# Essential APIs
EOF
    
    open_signup_page "https://runpod.io/signup" "RunPod"
    prompt_api_key "RUNPOD_API_KEY" "RunPod API Key" "true"
    
    open_signup_page "https://dash.cloudflare.com/sign-up" "Cloudflare"
    prompt_api_key "CLOUDFLARE_API_KEY" "Cloudflare API Key" "true"
    echo -n "Enter your Cloudflare email: "
    read cloudflare_email
    echo "CLOUDFLARE_EMAIL=$cloudflare_email" >> $ENV_FILE
    
    open_signup_page "https://github.com/signup" "GitHub"
    open_signup_page "https://github.com/settings/tokens/new" "GitHub Token"
    prompt_api_key "GITHUB_TOKEN" "GitHub Personal Access Token" "true"
    
    print_status "✅ Quick setup complete!"
    print_status "Essential APIs configured: RunPod, Cloudflare, GitHub"
    
elif [ "$1" = "--full" ]; then
    check_dependencies
    main
else
    check_dependencies
    main
fi
