"""Terradev CLI command base arguments for each MCP tool."""

TERRADEV_COMMAND_MAP = {
    "quote_gpu": ["quote"],
    "provision_gpu": ["terraform"],  # Now uses Terraform by default
    "preflight_provision": ["provision"],  # Dry-run preflight handled specially
    "terraform_plan": ["terraform", "plan"],
    "terraform_apply": ["terraform", "apply"],
    "terraform_destroy": ["terraform", "destroy"],
    "terraform_status": ["terraform", "status"],  # Fast state queries
    "k8s_create": ["k8s", "create"],
    "k8s_list": ["k8s", "list"],
    "k8s_info": ["k8s", "info"],
    "k8s_destroy": ["k8s", "destroy"],
    "inferx_deploy": ["inferx", "deploy"],
    "inferx_status": ["inferx", "status"],
    "inferx_list": ["inferx", "list"],
    "inferx_optimize": ["inferx", "optimize"],
    "hf_space_deploy": ["huggingface", "spaces", "create"],
    "status": ["status"],
    "manage_instance": ["manage"],
    "analytics": ["analytics"],
    "optimize": ["optimize"],
    "setup_provider": ["setup"],
    "configure_provider": ["configure"],
    # v3.4.0 tools
    "train": ["train"],
    "train_status": ["train-status"],
    "train_monitor": ["monitor"],
    "checkpoint_list": ["checkpoint", "list"],
    "checkpoint_save": ["checkpoint", "save"],
    "preflight": ["preflight"],
    # v3.2.0 tools
    "infer_route": ["inference", "route"],
    "infer_route_disagg": ["inference", "route"],
    "infer_status": ["inference", "status"],
    "infer_failover": ["inference", "failover"],
    "gpu_topology": ["inference", "topology"],
    "price_intel": ["analytics"],
    "moe_deploy": ["provision"],
    "gitops_init": ["gitops", "init"],
    # v2.0.0 tools — complete agentic loop
    "train_stop": ["train", "stop"],
    "train_resume": ["train", "resume"],
    "checkpoint_restore": ["checkpoint", "restore"],
    "checkpoint_promote": ["checkpoint", "promote"],
    "checkpoint_delete": ["checkpoint", "delete"],
    "stage": ["stage"],
    "infer_deploy": ["infer-deploy"],
    "up": ["up"],
    "rollback": ["rollback"],
    "manifests": ["manifests"],
    "smart_deploy": ["smart-deploy"],
    "helm_generate": ["helm-generate"],
    "gitops_bootstrap": ["gitops", "bootstrap"],
    "gitops_sync": ["gitops", "sync"],
    "gitops_validate": ["gitops", "validate"],
    "orchestrator_start": ["orchestrator", "start"],
    "orchestrator_register": ["orchestrator", "register"],
    "orchestrator_load": ["orchestrator", "load"],
    "orchestrator_evict": ["orchestrator", "evict"],
    "orchestrator_status": ["orchestrator", "status"],
    "orchestrator_infer": ["orchestrator", "infer"],
    "warm_pool_start": ["warm-pool", "start"],
    "warm_pool_status": ["warm-pool", "status"],
    "cost_scaler_start": ["cost-scaler", "start"],
    "cost_scaler_status": ["cost-scaler", "status"],
    "inferx_configure": ["inferx", "configure"],
    "inferx_delete": ["inferx", "delete"],
    "inferx_usage": ["inferx", "usage"],
    "inferx_quote": ["inferx", "quote"],
    "hf_space_status": ["huggingface", "spaces", "info"],
    "run_workflow": ["workflow", "run"],
    "active_context": ["status"],  # Composite — handled specially
    # v3.5.0: Multi-LoRA
    "lora_list": ["lora", "list"],
    "lora_add": ["lora", "add"],
    "lora_remove": ["lora", "remove"],
    # v4.0.0: ML Services — handled by custom elif blocks below
    "ray_status": ["ml", "ray", "status"],
    "ray_start": ["ml", "ray", "start"],
    "ray_stop": ["ml", "ray", "stop"],
    "ray_submit_job": ["ml", "ray", "submit"],
    "ray_list_jobs": ["ml", "ray", "jobs"],
    "ray_wide_ep_deploy": ["ml", "ray", "wide-ep"],
    "ray_disagg_pd_deploy": ["ml", "ray", "disagg-pd"],
    "ray_parallelism_strategy": ["ml", "ray", "parallelism"],
    "vllm_start": ["ml", "vllm", "start"],
    "vllm_stop": ["ml", "vllm", "stop"],
    "vllm_inference": ["ml", "vllm", "inference"],
    "vllm_info": ["ml", "vllm", "info"],
    "vllm_sleep": ["ml", "vllm", "sleep"],
    "vllm_wake": ["ml", "vllm", "wake"],
    # v5.0.0: SGLang Optimization Stack
    "sglang": ["ml", "sglang"],
    # v4.0.0: Legacy SGLang (deprecated)
    "sglang_start": ["ml", "sglang", "start"],
    "sglang_stop": ["ml", "sglang", "stop"],
    "sglang_inference": ["ml", "sglang", "inference"],
    "ollama_list": ["ml", "ollama", "list"],
    "ollama_pull": ["ml", "ollama", "pull"],
    "ollama_generate": ["ml", "ollama", "generate"],
    "ollama_chat": ["ml", "ollama", "chat"],
    "ollama_model_info": ["ml", "ollama", "info"],
    "ollama_ps": ["ml", "ollama", "ps"],
    "deepeval_run": ["ml", "deepeval", "run"],
    "deepeval_metrics": ["ml", "deepeval", "metrics"],
    "deepeval_evaluate": ["ml", "deepeval", "evaluate"],
    "deepeval_init": ["ml", "deepeval", "init"],
    "wandb_list_projects": ["ml", "wandb", "projects"],
    "wandb_list_runs": ["ml", "wandb", "runs"],
    "wandb_run_details": ["ml", "wandb", "run-details"],
    "mlflow_list_experiments": ["ml", "mlflow", "experiments"],
    "mlflow_log_run": ["ml", "mlflow", "log-run"],
    "mlflow_register_model": ["ml", "mlflow", "register"],
    "dvc_status": ["ml", "dvc", "status"],
    "dvc_diff": ["ml", "dvc", "diff"],
    "dvc_stage_checkpoint": ["ml", "dvc", "stage"],
    "dvc_push": ["ml", "dvc", "push"],
    "kserve_generate_yaml": ["ml", "kserve", "generate"],
    "kserve_list": ["ml", "kserve", "list"],
    "kserve_status": ["ml", "kserve", "status"],
    "egress_cheapest_route": ["egress", "route"],
    "egress_optimize_staging": ["egress", "optimize"],
    # v5.0.0: HuggingFace Hub — handled by custom elif blocks
    "hf_list_models": ["ml", "hf", "models"],
    "hf_list_datasets": ["ml", "hf", "datasets"],
    "hf_model_info": ["ml", "hf", "model-info"],
    "hf_create_endpoint": ["ml", "hf", "create-endpoint"],
    "hf_list_endpoints": ["ml", "hf", "list-endpoints"],
    "hf_endpoint_info": ["ml", "hf", "endpoint-info"],
    "hf_delete_endpoint": ["ml", "hf", "delete-endpoint"],
    "hf_endpoint_infer": ["ml", "hf", "endpoint-infer"],
    # v5.0.0: HF Smart Templates — handled by custom elif blocks
    "hf_smart_template": ["ml", "hf", "smart-template"],
    "hf_hardware_recommend": ["ml", "hf", "hardware-recommend"],
    "hf_hardware_compare": ["ml", "hf", "hardware-compare"],
    # v5.0.0: LangChain / LangGraph — handled by custom elif blocks
    "langchain_create_workflow": ["ml", "langchain", "workflow"],
    "langchain_create_sglang_pipeline": [
        "ml",
        "langchain",
        "sglang-pipeline",
    ],
    "langgraph_create_workflow": ["ml", "langgraph", "workflow"],
    "langgraph_orchestrator_worker": [
        "ml",
        "langgraph",
        "orchestrator-worker",
    ],
    "langgraph_evaluation_workflow": ["ml", "langgraph", "evaluation"],
    "langgraph_workflow_status": ["ml", "langgraph", "status"],
    # v5.0.0: W&B Enhanced — handled by custom elif blocks
    "wandb_create_dashboard": ["ml", "wandb", "create-dashboard"],
    "wandb_create_terradev_dashboard": [
        "ml",
        "wandb",
        "terradev-dashboard",
    ],
    "wandb_create_report": ["ml", "wandb", "create-report"],
    "wandb_create_terradev_report": ["ml", "wandb", "terradev-report"],
    "wandb_setup_alerts": ["ml", "wandb", "setup-alerts"],
    "wandb_create_terradev_alerts": ["ml", "wandb", "terradev-alerts"],
    "wandb_dashboard_status": ["ml", "wandb", "dashboard-status"],
    # v5.0.0: Data Governance — handled by custom elif blocks
    "governance_request_consent": ["governance", "consent-request"],
    "governance_record_consent": ["governance", "consent-record"],
    "governance_evaluate_opa": ["governance", "evaluate-opa"],
    "governance_move_data": ["governance", "move"],
    "governance_movement_history": ["governance", "history"],
    "governance_compliance_report": ["governance", "compliance-report"],
    # v5.0.0: Cost Optimizer Deep — handled by custom elif blocks
    "cost_analyze": ["cost", "analyze"],
    "cost_optimize_recommend": ["cost", "recommend"],
    "cost_simulate": ["cost", "simulate"],
    "cost_budget_optimize": ["cost", "budget-optimize"],
    # v5.0.0: Price Intelligence Extended — handled by custom elif blocks
    "price_trends": ["price", "trends"],
    "price_budget_optimize": ["price", "budget-optimize"],
    "price_spot_risk": ["price", "spot-risk"],
    # v5.0.0: Training Extended — handled by custom elif blocks
    "training_config_generate": ["train", "config-generate"],
    "training_launch_distributed": ["train", "launch-distributed"],
    "train_snapshot": ["train", "snapshot"],
    "train_detect_stragglers": ["train", "detect-stragglers"],
    # v5.0.0: Preflight Extended — handled by custom elif blocks
    "preflight_report": ["preflight", "report"],
    "preflight_gpu_check": ["preflight", "gpu-check"],
    "preflight_network_check": ["preflight", "network-check"],
    # v5.0.0: Kubernetes Enhanced — handled by custom elif blocks
    "k8s_gpu_operator_install": ["k8s", "gpu-operator"],
    "k8s_device_plugin": ["k8s", "device-plugin"],
    "k8s_mig_configure": ["k8s", "mig-configure"],
    "k8s_time_slicing": ["k8s", "time-slicing"],
    # v5.1.0: Datadog Integration — handled by custom elif blocks
    "datadog_status": ["datadog", "status"],
    "datadog_push_metrics": ["datadog", "push"],
    "datadog_send_event": ["datadog", "event"],
    "datadog_create_monitors": ["datadog", "monitors-create"],
    "datadog_list_monitors": ["datadog", "monitors-list"],
    "datadog_create_dashboard": ["datadog", "dashboard-create"],
    "datadog_list_dashboards": ["datadog", "dashboard-list"],
    "datadog_query": ["datadog", "query"],
    "datadog_terraform_export": ["datadog", "terraform-export"],
    "datadog_metric_catalog": ["datadog", "metric-catalog"],
    # v5.2.0: Phoenix / Guardrails / Qdrant
    "phoenix_test": ["phoenix", "test"],
    "phoenix_projects": ["phoenix", "projects"],
    "phoenix_spans": ["phoenix", "spans"],
    "phoenix_trace": ["phoenix", "trace"],
    "phoenix_otel_env": ["phoenix", "otel-env"],
    "phoenix_snippet": ["phoenix", "snippet"],
    "phoenix_k8s": ["phoenix", "k8s"],
    "guardrails_test": ["guardrails", "test"],
    "guardrails_chat": ["guardrails", "chat"],
    "guardrails_generate_config": ["guardrails", "generate-config"],
    "guardrails_k8s": ["guardrails", "k8s"],
    "qdrant_test": ["qdrant", "test"],
    "qdrant_collections": ["qdrant", "collections"],
    "qdrant_create_collection": ["qdrant", "create-collection"],
    "qdrant_info": ["qdrant", "info"],
    "qdrant_count": ["qdrant", "count"],
    "qdrant_k8s": ["qdrant", "k8s"],
    # v5.3.0: New v4.0.11 Features - Karpenter, Triggers, Environments, Lineage, Migration

    # v5.4.0: Langfuse LLM Observability
    "langfuse_configure": ["langfuse", "configure"],
    "langfuse_test": ["langfuse", "test"],
    "langfuse_traces": ["langfuse", "traces"],
    "langfuse_trace": ["langfuse", "trace"],
    "langfuse_scores": ["langfuse", "scores"],
    "langfuse_score": ["langfuse", "score"],
    "langfuse_datasets": ["langfuse", "datasets"],
    "langfuse_export_training_data": ["langfuse", "export-training-data"],
    "langfuse_quality": ["langfuse", "quality"],
    "langfuse_otel_env": ["langfuse", "otel-env"],
    "langfuse_k8s": ["langfuse", "k8s"],
    # v5.4.0: vLLM Extended
    "vllm_auto_optimize": ["vllm", "auto-optimize"],
    "vllm_analyze": ["vllm", "analyze"],
    "vllm_benchmark": ["vllm", "benchmark"],
    # v4.0.12: New ML Services and Enhanced Features
    "local_scan": ["local-scan"],
    # v6.0.4: Agentic tooling
    # v6.0.4: Agentic tooling
    "agent_agentic_serving_configure": ["agent", "agentic-serving", "configure"],
    "agent_agentic_serving_helm_values": ["agent", "agentic-serving", "helm-values"],
    "agent_agentic_serving_k8s": ["agent", "agentic-serving", "k8s"],
    "agent_agentic_serving_launch_args": ["agent", "agentic-serving", "launch-args"],
    "agent_agentic_serving_lmcache_env": ["agent", "agentic-serving", "lmcache-env"],
    "agent_agentic_serving_show_config": ["agent", "agentic-serving", "show-config"],
    "agent_cost": ["agent", "cost"],
    "agent_deploy": ["agent", "deploy"],
    "agent_langchain_create_langgraph": ["agent", "langchain", "create-langgraph"],
    "agent_langchain_create_pipeline": ["agent", "langchain", "create-pipeline"],
    "agent_langchain_create_workflow": ["agent", "langchain", "create-workflow"],
    "agent_langchain_test": ["agent", "langchain", "test"],
    "agent_langgraph_create_workflow": ["agent", "langgraph", "create-workflow"],
    "agent_langgraph_deploy": ["agent", "langgraph", "deploy"],
    "agent_langgraph_status": ["agent", "langgraph", "status"],
    "agent_langgraph_test": ["agent", "langgraph", "test"],
    "agent_letta_chat": ["agent", "letta", "chat"],
    "agent_letta_create": ["agent", "letta", "create"],
    "agent_letta_delete": ["agent", "letta", "delete"],
    "agent_letta_list": ["agent", "letta", "list"],
    "agent_letta_remember": ["agent", "letta", "remember"],
    "agent_letta_status": ["agent", "letta", "status"],
    "agent_list": ["agent", "list"],
    "agent_plan": ["agent", "plan"],
    "agent_scale": ["agent", "scale"],
    "agent_skill_attach": ["agent", "skill", "attach"],
    "agent_skill_init": ["agent", "skill", "init"],
    "agent_status": ["agent", "status"],
    "agent_teardown": ["agent", "teardown"],
    "agent_vector_db_down": ["agent", "vector-db", "down"],
    "agent_vector_db_up": ["agent", "vector-db", "up"],
    # v6.0.4: vLLM LoRA
    "ml_vllm_lora_link": ["ml", "vllm", "lora", "link"],
    "ml_vllm_lora_list": ["ml", "vllm", "lora", "list"],
    "ml_vllm_lora_load": ["ml", "vllm", "lora", "load"],
    "ml_vllm_lora_sync": ["ml", "vllm", "lora", "sync"],
    "ml_vllm_lora_unload": ["ml", "vllm", "lora", "unload"],
    "database_weaviate_create_collection": ["database", "weaviate", "create-collection"],
    "database_weaviate_delete_collection": ["database", "weaviate", "delete-collection"],
    "database_weaviate_hybrid_search": ["database", "weaviate", "hybrid-search"],
    "database_weaviate_insert": ["database", "weaviate", "insert"],
    "database_weaviate_list_collections": ["database", "weaviate", "list-collections"],
    "database_weaviate_query": ["database", "weaviate", "query"],
    "database_weaviate_up": ["database", "weaviate", "up"],
    "train_unsloth_run": ["train", "unsloth", "run"],
    "train_unsloth_start": ["train", "unsloth", "start"],
    "train_unsloth_stop": ["train", "unsloth", "stop"],
}
